import type { RecommendationItem } from "./recommendations";

// Dados de curadoria (sinopse detalhada, tags, plataforma, avaliação do público e obra relacionada)
// extraídos do catálogo completo de curadoria do Fanfarra. Mesclado ao CATALOG em recommendations.ts.
export const CURATION: Record<string, Partial<RecommendationItem>> = {
  rec_001_001: {
    synopsis: "Em um mundo onde cerca de 80% da população mundial possui alguma \"Individualidade\" (superpoderes), Izuku Midoriya nasceu sem qualquer habilidade especial. Apesar de sofrer discriminação e discriminação social, seu sonho inabalável de se tornar o maior herói do mundo chama a atenção do lendário All Might. Após demonstrar uma bravura genuína, Midoriya é escolhido como herdeiro do poder acumulativo 'One For All' e ingressa na prestigiada U.A. High School, onde enfrenta batalhas intensas contra a Aliança de Vilões e aprende o verdadeiro significado do heroísmo.",
    tags: ["Ação", "Superpoderes", "Escolar", "Shounen"],
    platform: "Crunchyroll",
    rating: 4,
    related: [{ id: "rec_002_008", title: "My Hero Academia", type: "Manga", relation: "Relacionado", source: "recommendations" }],
  },
  rec_001_002: {
    synopsis: "Durante o Período Taisho no Japão, Tanjiro Kamado é um jovem bondoso e trabalhador que ganha a vida vendendo carvão para sustentar sua família. Sua vida é despedaçada quando descobre que sua família foi brutalmente assassinada por demônios (Oni), e sua irmã caçula, Nezuko, é a única sobrevivente, embora tenha sido transformada em um demônio. Movido pela determinação e pelo amor fraterno, Tanjiro junta-se ao Esquadrão de Caçadores de Demônios para encontrar uma cura para Nezuko e derrotar Muzan Kibutsuji, o progenitor de todos os demônios.",
    tags: ["Ação", "Sobrenatural", "Histórico", "Shounen"],
    platform: "Crunchyroll, Netflix",
    rating: 4,
    related: [{ id: "rec_002_005", title: "Kimetsu no Yaiba", type: "Manga", relation: "Relacionado", source: "recommendations" }],
  },
  rec_001_003: {
    synopsis: "Gol D. Roger, o Rei dos Piratas, desencadeia a Grande Era dos Piratas ao anunciar no patíbulo a existência de seu tesouro supremo, o 'One Piece'. Anos depois, Monkey D. Luffy, um jovem que adquiriu propriedades de borracha ao comer a Akuma no Mi 'Gomu Gomu no Mi', parte para o mar em uma pequena embarcação. Reunindo uma tripulação diversificada e leal conhecida como os Chapéus de Palha, Luffy navega pela perigosa Grand Line em uma busca recheada de mistérios políticos, batalhas épicas, governos corruptos e laços indestrutíveis de amizade.",
    tags: ["Aventura", "Ação", "Fantasia", "Shounen"],
    platform: "Crunchyroll, Netflix",
    rating: 4.5,
    related: [{ id: "rec_002_003", title: "One Piece", type: "Manga", relation: "Relacionado", source: "recommendations" }],
  },
  rec_001_004: {
    synopsis: "Atsushi Nakajima é um jovem órfão expulso de seu orfanato e à beira da fome na cidade de Yokohama. Ao salvar um homem excêntrico chamado Osamu Dazai de um suposto afogamento, ele descobre que Dazai faz parte da Agência de Detetives Armados, um grupo cujos membros possuem habilidades sobrenaturais baseadas em grandes figuras da literatura mundial. Atsushi descobre ser o hospedeiro de um tigre místico e passa a integrar a agência, enfrentando guerras territoriais contra a máfia e organizações internacionais.",
    tags: ["Ação", "Mistério", "Sobrenatural", "Seinen"],
    platform: "Crunchyroll",
    rating: 4,
  },
  rec_001_005: {
    synopsis: "O time de basquete da Escola Seirin recebe dois calouros promissores: Taiga Kagami, um jogador vindo dos EUA com talento bruto impressionante, e Tetsuya Kuroko, um jovem aparentemente comum e sem presença física. Na verdade, Kuroko é o \"Sexto Homem Fantasma\" da lendária \"Geração dos Milagres\", um quinteto imbatível do ensino fundamental. Kuroko decide ser a \"sombra\" de Kagami para juntos superarem os antigos companheiros de Kuroko e levarem a Seirin ao topo do basquete escolar japonês.",
    tags: ["Esportes", "Escolar", "Shounen"],
    platform: "Netflix, Crunchyroll",
    rating: 4,
  },
  rec_001_006: {
    synopsis: "Iruma Suzuki é um garoto de 14 anos extremamente bonzinho e sem sorte, cujos pais irresponsáveis o vendem para Sullivan, um poderoso demônio do Submundo. No entanto, Sullivan não quer devorá-lo, mas sim adotá-lo como seu neto e mimá-lo. Matriculado na Escola de Demônios Babyls, Iruma precisa esconder sua condição de humano enquanto lida com colegas excêntricos, duelos de magia e incidentes inesperados, acabando por se tornar uma figura influente e adorada no mundo demoníaco.",
    tags: ["Comédia", "Fantasia", "Escolar", "Demônios"],
    platform: "Crunchyroll",
    rating: 4,
  },
  rec_001_007: {
    synopsis: "Rudo vive nas favelas de uma cidade próspera governada por elites, onde o lixo e os criminosos são jogados no \"Abismo\", uma fenda gigantesca da qual ninguém retorna. Acusado injustamente de assassinar seu pai adotivo, Rudo é atirado no Abismo. Lá embaixo, ele descobre um mundo devastado e perigoso, habitado por monstros feitos de lixo e por caçadores que utilizam objetos com valor sentimental (Vital Instrument) para manifestar poderes. Rudo jura voltar à superfície para se vingar de seus algozes.",
    tags: ["Ação", "Fantasia Urbana", "Shounen"],
    platform: "Crunchyroll",
    rating: 4,
    related: [{ id: "rec_002_012", title: "Gachiakuta", type: "Manga", relation: "Relacionado", source: "recommendations" }],
  },
  rec_001_008: {
    synopsis: "Yuji Itadori é um estudante do ensino médio com força física fora do comum. Após a morte de seu avô, ele se envolve com o Clube de Ocultismo de sua escola e acaba frente a frente com maldições reais originadas dos sentimentos negativos humanos. Para salvar seus amigos, Yuji engole um dedo amaldiçoado e torna-se o hospedeiro de Ryomen Sukuna, o lendário \"Rei das Maldições\". Para evitar sua execução imediata, ele se matricula no Colégio Técnico de Jujutsu de Tóquio sob a tutela de Satoru Gojo.",
    tags: ["Ação", "Sobrenatural", "Escolar", "Shounen"],
    platform: "Crunchyroll",
    rating: 4.5,
    related: [{ id: "rec_002_011", title: "Jujutsu Kaisen", type: "Manga", relation: "Relacionado", source: "recommendations" }],
  },
  rec_001_009: {
    synopsis: "Haruka Sakura é um jovem acostumado a ser rejeitado por sua aparência peculiar e por sua inclinação a brigas. Ele se transfere para a Fūrin High School, uma escola famosa por ter a pior reputação de delinquência da região, com o único objetivo de lutar para chegar ao topo. Ao chegar lá, descobre que a gangue da escola, apelidada de \"Bofurin\", transformou-se em uma patrulha comunitária dedicada a defender os moradores e o bairro contra gangues rivais e criminosos.",
    tags: ["Ação", "Delinquentes", "Escolar"],
    platform: "Crunchyroll",
    rating: 4,
  },
  rec_001_010: {
    synopsis: "Asta e Yuno foram abandonados juntos em uma igreja no Reino Clover. Em um mundo onde a magia é tudo, Yuno cresce como um prodígio dotado de um poder mágico incomparável, enquanto Asta nasce sem nenhum pingo de magia. No dia da cerimônia de concessão de grimórios, Yuno recebe o lendário grimório de quatro folhas, enquanto Asta recebe um misterioso grimório de cinco folhas contendo o poder da Anti-Magia. Ambos iniciam uma rivalidade saudável para ver quem se tornará o próximo Rei dos Magos.",
    tags: ["Ação", "Magia", "Shounen", "Fantasia"],
    platform: "Crunchyroll",
    rating: 4,
    related: [{ id: "rec_002_007", title: "Black Clover", type: "Manga", relation: "Relacionado", source: "recommendations" }],
  },
  rec_001_011: {
    synopsis: "Há mais de uma década, portais conectando o mundo humano a dimensões repletas de monstros começaram a surgir, dando origem aos \"Caçadores\", humanos com habilidades despertadas. Sung Jinwoo é conhecido como o \"Caçador Mais Fraco da Humanidade\" de Rank E, arriscando a vida em masmorras de nível baixo para pagar as despesas médicas de sua mãe. Após ser abandonado para morrer em uma masmorra dupla ultra-secreta, ele desperta com uma interface do \"Sistema\" que só ele consegue ver, permitindo-lhe subir de nível ilimitadamente.",
    tags: ["Ação", "Fantasia Urbana", "RPG", "Magia"],
    platform: "Crunchyroll",
    rating: 4,
    related: [{ id: "rec_003_001", title: "Solo Leveling", type: "Manhwa", relation: "Relacionado", source: "recommendations" }],
  },
  rec_001_012: {
    synopsis: "Naruto Uzumaki é um jovem órfão da Vila da Folha que cresceu isolado e rejeitado pelos moradores devido ao fato de ter a Raposa de Nove Caudas selada em seu corpo desde o nascimento. Para obter o respeito e o reconhecimento de todos, ele decide se tornar o Hokage, o líder supremo da vila. Acompanhado por Sasuke Uchiha e Sakura Haruno no Time 7 sob a liderança de Kakashi Hatake, Naruto enfrenta profundas conspirações geopolíticas, guerras ninjas e o desafio de trazer seu amigo de volta da escuridão.",
    tags: ["Ação", "Ninja", "Shounen", "Aventura"],
    platform: "Crunchyroll, Netflix",
    rating: 4,
  },
  rec_001_013: {
    synopsis: "Um fenômeno inexplicável conhecido como Combustão Humana Spontânea transforma cidadãos comuns em criaturas em chamas violentas chamadas \"Infernais\". Para combater essa ameaça, é criada a Companhia Especial de Bombeiros. Shinra Kusakabe, um jovem pirocinesista de terceira geração apelidado de \"Pegadas do Diabo\" devido à sua capacidade de acender os pés com fogo, entra para a 8ª Brigada com o objetivo de descobrir a causa do incêndio trágico que destruiu sua família na infância.",
    tags: ["Ação", "Sobrenatural", "Sci-Fi", "Shounen"],
    platform: "Crunchyroll",
    rating: 4,
    related: [{ id: "rec_001_014", title: "Soul Eater", type: "Anime", relation: "Relacionado", source: "recommendations" }],
  },
  rec_001_014: {
    synopsis: "Na Cidade da Morte, a Escola Técnica de Armas e Mestres Shinigami (DWMA) é gerida pelo próprio Deus da Morte. A instituição treina duplas formadas por \"Mestres\" e \"Armas Humanas\" (pessoas capazes de se transformar em armas). O objetivo principal é derrotar 99 almas humanas corrompidas e uma alma de bruxa para transformar a arma em uma \"Death Scythe\" digna de ser usada por Shinigami. A história acompanha Maka Albarn e seu parceiro Soul Eater em missões repletas de insanidade e batalhas estilizadas.",
    tags: ["Ação", "Fantasia", "Sobrenatural", "Escolar"],
    platform: "Crunchyroll",
    rating: 4,
    related: [{ id: "rec_001_013", title: "Fire Force", type: "Anime", relation: "Relacionado", source: "recommendations" }],
  },
  rec_001_015: {
    synopsis: "Shiki Ichinose é um jovem rebelde que adora armas e vive uma vida relativamente pacífica com seu pai adotivo. No entanto, sua rotina muda quando um assassino ataca sua casa e revela que Shiki carrega o sangue dos Oni (demônios). Após a morte de seu pai na batalha, Shiki descobre a existência de uma guerra milenar entre os descendentes de Oni e o grupo Momotaro, uma corporação impiedosa determinada a erradicar todos os Oni. Shiki junta-se a uma escola especial Oni para controlar seu sangue e lutar por liberdade.",
    tags: ["Ação", "Mitologia", "Sobrenatural"],
    platform: "Crunchyroll",
    rating: 3.5,
  },
  rec_001_016: {
    synopsis: "Satoru Mikami, um corporativo de 37 anos de Tóquio, é esfaqueado na rua por um assaltante ao proteger seu colega de trabalho. Enquanto morre, uma voz misteriosa interpreta seus últimos pensamentos e concede várias habilidades únicas. Ele desperta em uma caverna em um mundo de fantasia reencarnado como um slime. Batizado como Rimuru Tempest por um dragão tempestuoso, ele usa suas habilidades de \"Predador\" e \"Grande Sábio\" para fundar uma nação próspera e pacífica onde monstros e humanos possam coexistir em harmonia.",
    tags: ["Isekai", "Fantasia", "Magia", "Aventura"],
    platform: "Crunchyroll",
    rating: 4,
  },
  rec_001_017: {
    synopsis: "Coco é uma garota que vive em um vilarejo e sempre foi fascinada pela magia, embora neste mundo apenas aqueles nascidos bruxos possam praticá-la. Certo dia, ao espiar o bruxo Qifrey trabalhando, ela descobre o grande segredo: magia é desenhada com tintas especiais. Empolgada, Coco tenta desenhar uma figura de um livro antigo e acidentalmente petrifica sua própria mãe em um feitiço proibido. Qifrey decide acolhê-la como sua aprendiz para ajudá-la a reverter a maldição e protegê-la de uma facção sombria de bruxos.",
    tags: ["Fantasia", "Magia", "Seinen", "Aventura"],
    platform: "Crunchyroll",
    rating: 4,
  },
  rec_001_018: {
    synopsis: "Maomao trabalhava como apotecária no bairro da luz vermelha até ser sequestrada e vendida como serva de nível baixo para o Palácio Interior do Imperador. Inicialmente tentando manter um perfil discreto para cumprir seu contrato sem chamar atenção, sua insaciável curiosidade e vasto conhecimento sobre venenos e ervas medicinais vêm à tona quando os bebês imperiais começam a adoecer misteriosamente. Suas deduções chamam a atenção de Jinshi, um influente e atraente eunuco que a promove a provadora de comida e investigadora oficial da corte.",
    tags: ["Mistério", "Histórico", "Drama"],
    platform: "Crunchyroll",
    rating: 4.5,
  },
  rec_001_019: {
    synopsis: "Uma criatura misteriosa em formato de polvo destrói 70% da Lua e ameaça fazer o mesmo com a Terra em um ano. No entanto, ele faz uma exigência incomum: quer ser o professor da Turma 3-E da Escola Kunugigaoka, a classe de alunos desajustados e reprovados. O governo aceita e oferece uma recompensa de 10 bilhões de ienes para o aluno que conseguir assassiná-lo. Batizado de Koro-sensei, o monstro revela-se o melhor professor que aqueles jovens já tiveram, ensinando tanto matérias escolares quanto técnicas de assassinato.",
    tags: ["Ação", "Comédia", "Escolar", "Sci-Fi"],
    platform: "Crunchyroll",
    rating: 4,
  },
  rec_001_020: {
    synopsis: "Rintaro Tsumugi é um estudante da Chidori High, uma escola frequentada por rapazes vistos como delinquentes e fracassados pela sociedade. Ao lado fica a Kikyo Girls' High, um colégio de elite prestigiado e frequentado por garotas de famílias abastadas que desprezam a Chidori. Apesar dessa rivalidade histórica, Rintaro conhece Kaoruko Waguri no café de sua família. Conforme os dois se aproximam, eles precisam quebrar os preconceitos deeply impregnados em seus ambientes e colegas para proteger o vínculo genuíno que nasceu entre eles.",
    tags: ["Romance", "Drama", "Escolar"],
    platform: "Crunchyroll",
    rating: 4,
  },
  rec_001_021: {
    synopsis: "Por mais de um século, os últimos remanescentes da humanidade viveram confinados dentro de três gigantescas muralhas circulares para se protegerem dos Titãs, seres gigantescos sem inteligência aparente que devoram humanos. Eren Yeager, sua irmã adotiva Mikasa e seu amigo Armin testemunham a destruição da muralha externa por um Titã Colossal e o massacre de sua mãe. Tomado pelo ódio, Eren jura erradicar cada Titã da face da Terra e junta-se à Divisão de Reconhecimento, descobrindo segredos aterrorizantes sobre a verdadeira origem do mundo.",
    tags: ["Ação", "Drama", "Mistério", "Fantasia Sombria"],
    platform: "Crunchyroll",
    rating: 4.5,
    related: [{ id: "rec_002_013", title: "Attack on Titan", type: "Manga", relation: "Relacionado", source: "recommendations" }],
  },
  rec_001_022: {
    synopsis: "Clevatess é um dos quatro Senhores Demônios supremos, possuindo um poder avassalador e inteligência incomparável. Irritado com a audácia dos heróis humanos que invadiram seu domínio para tentar assassiná-lo, Clevatess decide exterminar a raça humana inteira. Contudo, momentos antes de iniciar o massacre, o destino coloca sob seus cuidados um bebê humano recém-nascido. Curioso sobre a natureza frágil dessa espécie, o Senhor Demônio decide adiar o apocalipse e parte em uma jornada disfarçado no mundo humano para criar a criança e entender a humanidade.",
    tags: ["Fantasia Sombria", "Ação", "Demônios"],
    platform: "Crunchyroll",
    rating: 4,
  },
  rec_001_023: {
    synopsis: "Ryo morre na Terra e desperta em um mundo de fantasia reencarnado com uma afinidade excepcional para a Magia de Água, um elemento geralmente considerado secundário se comparado ao fogo ou ao trovão. Decidido a viver uma vida tranquila e autossuficiente, Ryo isola-se em uma floresta perigosa por anos, aprimorando seu controle e criando técnicas aquáticas sem precedentes de nível divino. Quando ele finalmente decide explorar a civilização, sua potência incomparável choca aventureiros, magos e monarcas por onde passa.",
    tags: ["Fantasia", "Magia", "Isekai"],
    platform: "Crunchyroll",
    rating: 3.5,
  },
  rec_001_024: {
    synopsis: "Yoshiki e Hikaru são dois adolescentes que cresceram juntos em um pequeno vilarejo rural cercado por montanhas isoladas. Um dia, Hikaru desaparece na montanha por uma semana e retorna parecendo normal, mas Yoshiki percebe imediatamente que o ser que voltou vestindo a pele de seu melhor amigo não é humano, mas uma entidade antiga e sobrenatural. Apesar do horror e do perigo iminente que essa criatura representa para o vilarejo, Yoshiki recusa-se a se afastar do 'falso Hikaru', preso em um turbilhão de luto, dependência emocional e mistério.",
    tags: ["Terror", "Mistério", "Sobrenatural", "Drama"],
    platform: "Crunchyroll",
    rating: 4.5,
  },
  rec_002_001: {
    synopsis: "Saitama é um herói por hobby que treinou tanto durante três anos que perdeu todos os cabelos de sua cabeça e tornou-se incrivelmente poderoso, capaz de derrotar qualquer vilão ou monstro gigante com apenas um único soco. Essa invencibilidade transformou sua vida em um tédio profundo, desprovido do entusiasmo e da adrenalina da batalha. Ao lado de seu discípulo ciborgue Genos, Saitama entra para a Associação de Heróis, lidando com a burocracia dos super-heróis enquanto busca secretamente por um adversário que consiga fazê-lo lutar a sério.",
    tags: ["Ação", "Comédia", "Super-heróis", "Seinen"],
    platform: "MANGA Plus",
    rating: 4,
  },
  rec_002_002: {
    synopsis: "Momo Ayase é uma colegial que acredita firmemente em fantasmas e espíritos, mas recusa-se a acreditar em alienígenas. Seu colega de classe Ken Takakura (apelidado de Okarun) acredita cegamente em extraterrestres, mas desdenha de assuntos sobrenaturais. Para provar quem está certo, ambos aceitam o desafio de visitar locais assombrados por discos voadores e espíritos respectivamente. Para a surpresa de ambos, descobre-se que tanto alienígenas com tecnologias bizarras quanto espíritos vingativos são reais, unindo os dois em uma batalha frenética repleta de maldições e ação.",
    tags: ["Ação", "Sobrenatural", "Aliens", "Comédia"],
    platform: "MANGA Plus",
    rating: 4,
  },
  rec_002_003: {
    synopsis: "A grandiosa obra em quadrinhos escrita e ilustrada por Eiichiro Oda narra com riqueza de detalhes geopolíticos, históricos e culturais a jornada de Monkey D. Luffy. O mangá aprofunda temas como o Século Perdido, os 20 Reis Fundadores do Governo Mundial, as Armas Antigas e a vontade herdada do 'D'. A narrativa destaca as especificidades de cada ilha da Grand Line e do Novo Mundo, mostrando o impacto das ações dos Chapéus de Palha na estrutura política global dos mares.",
    tags: ["Aventura", "Ação", "Piratas", "Shounen"],
    platform: "MANGA Plus",
    rating: 4.5,
    related: [{ id: "rec_001_003", title: "One Piece", type: "Anime", relation: "Relacionado", source: "recommendations" }],
  },
  rec_002_004: {
    synopsis: "Takemichi Hanagaki é um jovem de 26 anos na pior fase da vida, trabalhando num emprego ruim e vivendo num apartamento caindo aos pedaços. Ele descobre pela TV que sua única namorada dos tempos de escola, Hinata Tachibana, foi morta em um confronto da gangue Tokyo Manji (Toman). Após ser empurrado nos trilhos do trem, em vez de morrer, Takemichi viaja 12 anos no tempo até seus anos de ensino fundamental. Ele percebe que pode alterar o futuro e jura subir na hierarquia da gangue para salvar a vida de Hinata.",
    tags: ["Ação", "Viagem no Tempo", "Delinquentes"],
    platform: "Kodansha / MANGA Plus",
    rating: 4,
  },
  rec_002_005: {
    synopsis: "O mangá original escrito por Koyoharu Gotouge detalha a arte da espada e os Estilos de Respiração (Água, Fogo, Trovão, Névoa, Pedra, etc.) utilizados pelos Caçadores de Demônios. A obra explora com profundidade o passado trágico e a humanidade esquecida de cada demônio derrotado por Tanjiro, além de mostrar em detalhes as táticas dos Hashiras para invadir o Castelo Infinito e exterminar Muzan Kibutsuji de uma vez por todas.",
    tags: ["Ação", "Sobrenatural", "Histórico", "Shounen"],
    platform: "MANGA Plus",
    rating: 4.5,
    related: [{ id: "rec_001_002", title: "Demon Slayer", type: "Anime", relation: "Relacionado", source: "recommendations" }],
  },
  rec_002_006: {
    synopsis: "O Japão possui o maior índice de surgimento de monstros gigantes (\"Kaijus\") do mundo. Kafka Hibino sonhava em ingressar na Força de Defesa para lutar ao lado de sua amiga de infância Mina Ashiro, mas falhou nos testes e acabou trabalhando na Monster Sweeper, empresa responsável pela limpeza dos restos mortais dos monstros. Um dia, uma pequena criatura Kaiju entra pela sua boca, concedendo-lhe a capacidade de se transformar no lendário \"Kaiju Nº 8\", um monstro de classe histórica com força devastadora.",
    tags: ["Ação", "Monstros", "Sci-Fi", "Shounen"],
    platform: "MANGA Plus",
    rating: 4,
  },
  rec_002_007: {
    synopsis: "No mangá de Yūki Tabata, a arte detalhada enfatiza as batalhas em equipe e a evolução do grimório de Anti-Magia de Asta. A obra mergulha na história secreta do Reino Clover, nas discriminações entre a nobreza e os camponeses, na invasão do Reino de Spade e no confronto definitivo contra os demônios do Submundo e seus hospedeiros da Triade das Sombras.",
    tags: ["Ação", "Magia", "Fantasia", "Shounen"],
    platform: "MANGA Plus",
    rating: 4,
    related: [{ id: "rec_001_010", title: "Black Clover", type: "Anime", relation: "Relacionado", source: "recommendations" }],
  },
  rec_002_008: {
    synopsis: "O quadrinho original explora profundamente a desconstrução da Sociedade de Heróis e as rachaduras causadas pela dependência excessiva no \"Símbolo da Paz\". A história se desenvolve através das tragédias pessoais de vilões como Tomura Shigaraki e Dabi, culminando em uma guerra total em grande escala que põe à prova a responsabilidade coletiva de toda a sociedade.",
    tags: ["Ação", "Super-heróis", "Escolar", "Shounen"],
    platform: "MANGA Plus",
    rating: 4,
    related: [{ id: "rec_001_001", title: "My Hero Academia", type: "Anime", relation: "Relacionado", source: "recommendations" }],
  },
  rec_002_009: {
    synopsis: "O agente \"Twilight\", o maior espião da nação de Westalis, precisa cumprir a Operação Strix para evitar uma guerra com a vizinha Ostania. Para se aproximar do alvo político, ele adota a identidade de Loid Forger e precisa arranjar uma esposa e um filho em menos de uma semana. Ele adota Anya, uma garotinha telepata, e se casa com Yor Briar, uma dedicada funcionária pública que à noite atua como a temida assassina \"Princesa dos Espinhos\". Nenhum deles conhece o segredo do outro, gerando situações cômicas e comoventes.",
    tags: ["Comédia", "Espionagem", "Família", "Ação"],
    platform: "MANGA Plus",
    rating: 4.5,
  },
  rec_002_010: {
    synopsis: "Denji é um jovem extremamente pobre que vive pagando as dívidas astronômicas deixadas por seu falecido pai, trabalhando como caçador de demônios ilegais ao lado de Pochita, o Demônio da Motosserra. Após ser traído e assassinado pela Yakuza, Pochita se funde ao coração de Denji para salvá-lo, transformando-o num híbrido de demônio. Recrutado por Makima para a Segurança Pública, Denji busca alcançar desejos simples e humanos enquanto enfrenta demônios conceituais aterrorizantes como o Demônio do Armamento e do Controle.",
    tags: ["Ação", "Horror", "Fantasia Sombria", "Shounen"],
    platform: "MANGA Plus",
    rating: 4.5,
  },
  rec_002_011: {
    synopsis: "A versão em mangá de Gege Akutami apresenta um sistema de poder altamente técnico e detalhado focado na Energia Amaldiçoada e na Expansão de Domínio. A obra acompanha arcos dramáticos como o Incidente de Shibuya e o Culling Game (Jogo do Abate), mostrando o colapso do mundo dos xamãs e o plano milenar de Kenjaku para forçar a evolução da humanidade através de maldições.",
    tags: ["Ação", "Maldições", "Sobrenatural", "Shounen"],
    platform: "MANGA Plus",
    rating: 4,
    related: [{ id: "rec_001_008", title: "Jujutsu Kaisen", type: "Anime", relation: "Relacionado", source: "recommendations" }],
  },
  rec_002_012: {
    synopsis: "Com traços dinâmicos e expressivos influenciados pela arte urbana e o grafite, o mangá de Kei Urana constrói uma crítica social afiada sobre o consumismo e o descarte desmedido. A narrativa foca na jornada de Rudo para dominar suas luvas mágicas e desvendar a verdade por trás dos \"Zodycs\" e da fronteira que separa a cidade limpa da superfície do mundo de dejetos abaixo dela.",
    tags: ["Ação", "Fantasia", "Arte", "Shounen"],
    platform: "Kodansha",
    rating: 4,
    related: [{ id: "rec_001_007", title: "Gachiakuta", type: "Anime", relation: "Relacionado", source: "recommendations" }],
  },
  rec_002_013: {
    synopsis: "A obra em quadrinhos completa de Hajime Isayama desenrola uma complexa teia de geopolítica, segredos de sangue e traumas geracionais entre Eldia e Marley. A narrativa foca nas dilemas morais da guerra, na busca desesperada por liberdade e nas consequências devastadoras do \"Rumbling\" (O Estrondo), onde milhares de Titãs Colossais marcham para pisotear o mundo fora da ilha de Paradis.",
    tags: ["Ação", "Mistério", "Fantasia Sombria", "Drama"],
    platform: "Kodansha",
    rating: 4.5,
    related: [{ id: "rec_001_021", title: "Attack on Titan", type: "Anime", relation: "Relacionado", source: "recommendations" }],
  },
  rec_003_001: {
    synopsis: "A webcomic sul-coreana retrata a ascensão meteórica de Sung Jinwoo. Após ser escolhido pelo \"Sistema\", Jinwoo passa por treinos diários rigorosos e desafios em masmorras de classe especial. A história desdobra a guerra ancestral entre os Monarcas (entidades da destruição) e os Governantes (defensores da ordem), revelando que Jinwoo é a peça chave para salvar a Terra ao se tornar o lendário Monarca das Sombras comandando um exército de soldados mortos-vivos.",
    tags: ["Ação", "Fantasia Urbana", "RPG", "Caçadores"],
    platform: "Webtoon, Tapas",
    rating: 4.5,
    related: [{ id: "rec_001_011", title: "Solo Leveling", type: "Anime", relation: "Relacionado", source: "recommendations" }],
  },
  rec_003_002: {
    synopsis: "Kim Dokja é um funcionário de escritório comum cujo único hobby durante dez anos foi ler a webnovel apocalíptica 'Três Formas de Sobreviver em um Mundo Arruinado'. Quando o capítulo final é publicado, o mundo real subitamente se transforma no cenário exato do livro. Dokja torna-se a única pessoa no planeta que sabe exatamente o que acontecerá a cada arco, usando seu conhecimento prévio e inteligência para manipular os 'Cenários', lidar com os 'Constelações' (deuses e demônios espectadores) e proteger o protagonista original da história.",
    tags: ["Ação", "Apocalipse", "Fantasia", "Sistema"],
    platform: "Webtoon",
    rating: 4.5,
    related: [{ id: "rec_010_006", title: "Omniscient Reader's Viewpoint", type: "Webtoon", relation: "Relacionado", source: "recommendations" }],
  },
  rec_003_003: {
    synopsis: "Suho Kim é um estudante de engenharia civil na Coreia do Sul que, ao adormecer lendo uma novel de fantasia medieval, acorda no corpo de Lloyd Frontera, um nobre folgado, beberrão e odiado por todos, cuja família está atolada em dívidas gigantescas. Usando seus conhecimentos técnicos de arquitetura, mecânica e engenharia, além de fazer contratos com espíritos elementais, Lloyd cria sistemas de saneamento, pontes e aquecimento para transformar seu domínio em uma potência econômica e salvar seu próprio futuro de forma hilária.",
    tags: ["Comédia", "Fantasia", "Construção", "Isekai"],
    platform: "Webtoon",
    rating: 4.5,
  },
  rec_003_004: {
    synopsis: "O Rei Grey possuía força, riqueza e prestígio inigualáveis em um mundo militarizado, mas vivia solitário e desprovido de propósito. Após sua morte misteriosa, ele reencarna no continente mágico de Dicathen como Arthur Leywin, um bebê que conserva as memórias e a disciplina de sua vida anterior. Aprendendo a controlar a mana desde a infância, Arthur treina com dragões e ingressa na academia de magos, preparando-se para defender seu novo mundo contra a invasão iminente dos 'Vritra', seres divinos sombrios de outro continente.",
    tags: ["Fantasia", "Reencarnação", "Magia", "Ação"],
    platform: "Tapas",
    rating: 4.5,
  },
  rec_003_005: {
    synopsis: "Chung Myung, o 13º Discípulo do Santo da Espada da Seita Mount Hua, sacrificou sua vida para derrotar o temível Líder da Seita Demoníaca Chun Ma e salvar o mundo. Cem anos após sua morte, ele desperta no corpo de um jovem órfão e descobre que sua amada Seita Mount Hua declinou completamente, perdendo suas técnicas sagradas, riqueza e prestígio. Determinado a honrar o legado de seus antigos irmãos de espadas, Chung Myung usa seus conhecimentos e métodos de treinamento rigorosos e cômicos para erguer a seita ao topo novamente.",
    tags: ["Artes Marciais", "Murim", "Reencarnação", "Comédia"],
    platform: "Webtoon",
    rating: 4.5,
  },
  rec_003_006: {
    synopsis: "Cheon Yeo-Woon é um filho ilegítimo do Líder do Culto Demoníaco que cresce sofrendo constante perseguição e tentativas de assassinato por parte das esposas oficiais do líder. À beira da morte em uma emboscada, ele é salvo por um descendente do futuro distante que injeta em suas veias uma máquina de nanomáquinas de última geração (Nano Machine). A inteligência artificial integrada permite que Yeo-Woon analise artes marciais instantaneamente, cure ferimentos fatais e otimize seu corpo para se tornar o mestre supremo do culto.",
    tags: ["Artes Marciais", "Murim", "Sci-Fi", "Vingança"],
    platform: "Webtoon",
    rating: 4,
  },
  rec_003_007: {
    synopsis: "Confúcio Kim é um caçador de Rank F frustrado e invejoso da fama do número um do ranking, o \"Flame Emperor\". Seu desejo ardente atrai uma habilidade de classe SSS extremamente bizarra: a capacidade de copiar uma habilidade do seu assassino toda vez que for morto. No entanto, ele é imediatamente assassinado pelo próprio Flame Emperor e descobre o efeito colateral da sua habilidade: ele retorna 24 horas no tempo a cada morte. Morrendo mais de 4.000 vezes de propósito, ele retorna anos ao passado para reescrever o destino de todos na Torre.",
    tags: ["Ação", "RPG", "Fantasia", "Regressão"],
    platform: "Tapas",
    rating: 4.5,
  },
  rec_003_008: {
    synopsis: "O 'Mundo das Sombras' devastou a Terra durante dez anos, culminando no confronto final dentro do Labirinto das Sombras. Apenas seis caçadores sobreviveram, incluindo Desir Arman, um dos magos analistas mais brilhantes de sua era. Quando a missão falha e o núcleo explode, Desir acorda 13 anos no passado, de volta aos seus dias de calouro na prestigiada Academia de Magia Hebrion. Sabendo das falhas catastróficas do sistema de ensino que marginalizava alunos comuns, Desir recruta aliados talentosos para salvar o futuro.",
    tags: ["Fantasia", "Magia", "Regressão", "Ação"],
    platform: "Tapas",
    rating: 4,
  },
  rec_003_009: {
    synopsis: "Zephyr é o último guerreiro sobrevivente da humanidade em um mundo destruído pelas invasões de demônios. Mesmo lutando desesperadamente, ele é derrotado em combate pelo Deus da Destruição, Tartarus. Impressionados com sua bravura e entretidos por sua luta, os Deuses do Olimpo e de outras mitologias concedem a Zephyr uma segunda chance: retornar dez anos no passado com todas as suas memórias e conhecimentos intactos para se preparar melhor, salvar seus entes queridos e matar os deuses que usam a humanidade como diversão.",
    tags: ["Ação", "Fantasia", "Regressão", "Deuses"],
    platform: "Webtoon",
    rating: 4,
  },
  rec_003_010: {
    synopsis: "Jin Tae-Kyung é um caçador de monstros de nível baixo na era moderna que mal consegue pagar o aluguel. Durante um trabalho de limpeza, ele encontra um misterioso dispositivo de Realidade Virtual antigo. Ao ligar o aparelho, sua consciência é transferida para o Murim (o mundo das artes marciais da China Antiga). Nesse mundo, ele precisa treinar e sobreviver sob a perspectiva de um filho fracassado de uma família influente. As habilidades e atributos que ele conquista no Murim transferem-se diretamente para seu corpo no mundo real.",
    tags: ["Artes Marciais", "VRMMO", "Ação", "Comédia"],
    platform: "Tapas",
    rating: 4,
  },
  rec_004_001: {
    synopsis: "Zhuo Yifan era o Imperador Demônio mais temido e poderoso do mundo do cultivo, mas foi traído e assassinado por seu próprio discípulo confiável ao encontrar o Livro dos Segredos do Imperador Sagrado. Sua alma sobrevive e reencarna no corpo de Zhuo Fan, um jovem servo sem cultivo pertencente à decadente Família Luo. Devido a uma promessa de sangue deixada pelo antigo dono do corpo, Zhuo Fan é forçado a atuar como o mordomo da família, usando suas táticas maquiavélicas e sabedoria demoníaca para erguer os Luo ao poder supremo.",
    tags: ["Xianxia", "Cultivo", "Anti-herói", "Reencarnação"],
    platform: "Bilibili Comics",
    rating: 4,
  },
  rec_004_002: {
    synopsis: "No Continente Dou Qi, a força individual determina a reputação e o respeito de um indivíduo. Xiao Yan era considerado um prodígio incomparável em sua vila, tendo alcançado níveis lendários de cultivo ainda na infância. De repente, aos 10 anos, seu poder começou a regredir misteriosamente, fazendo com que ele se tornasse a chacota da região e perdesse o noivado com uma nobre. Ele descobre que a causa do problema é um anel antigo que carrega a alma de Yao Chen, um mestre alquimista lendário que passa a treiná-lo na arte das Chamas Celestiais.",
    tags: ["Cultivo", "Artes Marciais", "Fantasia", "Ação"],
    platform: "Bilibili Comics",
    rating: 4,
  },
  rec_004_003: {
    synopsis: "Tang San era um dos discípulos mais talentosos da famosa seita de artes marciais e fabricação de armas ocultas Tang Sect. Ao roubar os ensinamentos proibidos da seita para atingir o ápice da arte, ele comete suicídio saltando de um penhasco para provar sua lealdade. Ele reencarna no Continente Douluo, onde não existem artes marciais tradicionais, mas sim \"Almas Guerreiras\". Ao despertar a desacreditada \"Grama Azul de Prata\" e a lendária \"Martelo do Céu Claro\", Tang San inicia uma jornada revolucionária para fundar a Seita Tang neste novo mundo.",
    tags: ["Fantasia", "Ação", "Cultivo", "Espíritos"],
    platform: "WeComics",
    rating: 4,
    related: [{ id: "rec_011_004", title: "Soul Land", type: "Donghua", relation: "Relacionado", source: "recommendations" }],
  },
  rec_004_004: {
    synopsis: "Nie Li era o mais forte Espiritualista de Demonios de sua era, mas foi derrotado ao lado de seus companheiros durante o ataque devastador do Imperador Sábio e de seis bestas de nível divino. No instante de sua morte, sua alma é transportada de volta ao tempo em que ele tinha 13 anos de idade e estudava na Academia da Cidade da Glória. Conservando todos os seus conhecimentos sobre cultivação, alquimia e padrões de matrizes espirituais, Nie Li decide mudar o futuro, proteger sua cidade natal da destruição e salvar a garota que amava.",
    tags: ["Cultivo", "Regressão", "Magia", "Fantasia"],
    platform: "Bilibili Comics",
    rating: 4,
  },
  rec_004_005: {
    synopsis: "A jornada para o topo do cultivo marcial é longa, solitária e impiedosa. Yang Kai era um simples servo encarregado da limpeza na High Heaven Pavilion, incapacitado de avançar em seus treinos devido a uma limitação em seu corpo. Um dia, ele encontra um Livro Negro sem texto que se funde ao seu corpo e transforma sua constituição física. A partir desse momento, Yang Kai inicia uma caminhada implacável de superação, enfrentando seitas rivais, explorando diferentes reinos e dimensões até atingir o ápice do universo marcial.",
    tags: ["Cultivo", "Artes Marciais", "Harem", "Ação"],
    platform: "Bilibili Comics",
    rating: 4,
  },
  rec_004_006: {
    synopsis: "Gu Changge desperta em um mundo de cultivo Xianxia descobrindo que reencarnou no corpo de um \"Jovem Mestre Vilão\" de uma família sagrada e influente. Em vez de desesperar-se por estar destinado a ser derrotado pelos \"Filhos do Destino\" (os protagonistas com sorte absurda típicos de histórias de cultivo), Changge ganha um Sistema do Vilão Supremo. Ele passa a usar sua inteligência, autoridade e manipulação sociopata para roubar a sorte dos protagonistas, manipular heroínas e devorar as fontes de poder de seus inimigos sem piedade.",
    tags: ["Xianxia", "Vilão", "Sistema", "Cultivo"],
    platform: "Bilibili Comics",
    rating: 4,
  },
  rec_005_001: {
    synopsis: "Um homem misterioso conhecido como \"O Professor\" passa anos planejando o maior assalto da história: invadir a Casa da Moeda da Espanha e imprimir 2,4 bilhões de euros em cédulas não rastreáveis. Para executar o plano, ele recruta oito criminosos com habilidades específicas e nomes de cidades como codinomes. A série acompanha os 11 dias de reclusão dentro da instituição, onde o grupo lida com dezenas de reféns, negociações psicológicas com a inspetora Raquel Murillo e regras rígidas estipuladas pelo Professor para manipular a opinião pública.",
    tags: ["Crime", "Assalto", "Drama", "Suspense"],
    platform: "Netflix",
    rating: 4,
  },
  rec_005_002: {
    synopsis: "Uma jovem veste um headset de realidade virtual e descobre que sua mente foi transferida permanentemente para um mundo digital com temática de circo infantil dos anos 90. Ela ganha um novo corpo em formato de boba da corte e o nome Pomni. Administrado por Caine, uma inteligência artificial excêntrica e imprevisível, o circo é um confinamento sem saída onde outros humanos aprisionados tentam manter a sanidade através de aventuras cotidianas absurdas para evitar a \"abstração\" (a perda completa da mente para a loucura).",
    tags: ["Animação", "Surrealismo", "Comédia Negra"],
    platform: "YouTube",
    rating: 4,
  },
  rec_005_003: {
    synopsis: "Barry Allen é um perito forense da polícia de Central City traumatizado pelo assassinato misterioso de sua mãe na infância. Após a explosão do Acelerador de Partículas dos laboratórios S.T.A.R., Barry é atingido por um raio combinado com produtos químicos e fica em coma por nove meses. Ao acordar, descobre que adquiriu supervelocidade sobre-humana e conexões com a \"Força de Aceleração\". Ao lado do Dr. Harrison Wells e sua equipe, Barry assume a identidade de Flash para combater outros meta-humanos que usam seus poderes para o crime.",
    tags: ["Ação", "Super-heróis", "Sci-Fi", "DC"],
    platform: "Netflix / Max",
    rating: 4,
  },
  rec_005_004: {
    synopsis: "Sam Gardner é um jovem de 18 anos no espectro autista que adora a Antártida e biologia marinha. Ao decidir que é hora de começar a namorar e buscar mais independência em relação à sua família, sua jornada de autodescoberta força sua mãe superprotetora Elsa, seu pai Hank e sua irmã atleticamente talentosa Casey a reavaliarem suas próprias vidas e relacionamentos. A série equilibra momentos cômicos e sensíveis sobre empatia, amadurecimento e dinâmicas familiares.",
    tags: ["Comédia", "Drama", "Família", "Autismo"],
    platform: "Netflix",
    rating: 4,
  },
  rec_005_005: {
    synopsis: "Baseada no universo de League of Legends, a série narra as origens e a ruína da relação entre duas irmãs, Vi e Powder (Jinx), em meio às crescentes tensões sociais entre a rica e utópica cidade de Piltover e a sub-cidade oprimida e tóxica de Zaun. A descoberta da tecnologia 'Hextech' em Piltover (magia controlada pela ciência) e a proliferação da droga mutagênica 'Cintila' em Zaun acendem o estopim de uma guerra política, ideológica e familiar devastadora.",
    tags: ["Animação", "Sci-Fi", "Steampunk", "Drama"],
    platform: "Netflix",
    rating: 4.5,
  },
  rec_005_006: {
    synopsis: "Em outubro de 1989, 43 mulheres ao redor do mundo deram à luz simultaneamente sem apresentarem sinais prévios de gravidez. O bilionário excêntrico Sir Reginald Hargreeves adota sete dessas crianças e funda a Umbrella Academy, treinando-as para salvar o mundo com seus poderes extraordinários. Anos após a dissolução do grupo, os irmãos traumatizados e distanciados se reúnem para o funeral do pai adotivo e descobrem que têm apenas oito dias para impedir um apocalipse global iminente.",
    tags: ["Superpoderes", "Família", "Sci-Fi", "Comédia"],
    platform: "Netflix",
    rating: 4,
  },
  rec_005_007: {
    synopsis: "Ryohei Arisu é um jovem desempregado e viciado em videogames que passa os dias perambulando com seus dois melhores amigos por Tóquio. Após se esconderem em um banheiro público durante uma confusão na estação de Shibuya, eles saem e encontram a metrópole completamente deserta. Para sobreviver neste novo mundo chamado \"Borderland\", eles são forçados a participar de jogos letais divididos por naipes de cartas (Força, Trabalho em Equipe, Inteligência e Traição Psicologia) para estender a validade de seus \"vistos\" de vida.",
    tags: ["Sobrevivência", "Jogos", "Suspense", "Sci-Fi"],
    platform: "Netflix",
    rating: 4,
  },
  rec_005_008: {
    synopsis: "Seong Gi-hun é um homem divorciado, atolado em dívidas astronômicas de jogo e à beira de perder a custódia da filha. Ele recebe um convite misterioso para participar de uma competição secreta ao lado de outras 455 pessoas em situação financeira desesperadora. O prêmio final é de 45,6 bilhões de wons, mas os participantes logo descobrem que os jogos são brincadeiras infantis tradicionais coreanas adaptadas com regras fatais: quem é eliminado é executado sumariamente no local.",
    tags: ["Sobrevivência", "Thriller", "Drama", "Ação"],
    platform: "Netflix",
    rating: 4,
  },
  rec_005_009: {
    synopsis: "O voo 828 da Montego Air decolou da Jamaica rumo a Nova York com 191 passageiros a bordo e enfrentou uma turbulência severa e inexplicável no caminho. Ao pousarem com segurança, os passageiros descobre que, para o restante do mundo, se passaram cinco anos e meio durante os quais eles foram dados como mortos. Enquanto tentam se reintegrar à sociedade, os sobreviventes começam a ouvir vozes e ter visões conhecidas como \"Chamados\", que os guiam para resolver mistérios e salvar vidas, apontando para uma data de expiração iminente.",
    tags: ["Mistério", "Sci-Fi", "Drama", "Sobrenatural"],
    platform: "Netflix",
    rating: 3.5,
  },
  rec_005_010: {
    synopsis: "Charlie Spring é um jovem assumidamente gay e reservado que estuda na Truham Grammar School após ter enfrentado um ano difícil de bullying. Ele é designado para sentar ao lado de Nick Nelson, um garoto carismático, popular e estrela do time de rugby da escola. Uma amizade calorosa surge rapidamente entre os dois, transformando-se em um sentimento mais profundo à medida que Nick começa a explorar e entender sua própria sexualidade com o apoio de seu círculo de amigos.",
    tags: ["Romance", "LGBTQ+", "Escolar", "Drama"],
    platform: "Netflix",
    rating: 4.5,
  },
  rec_005_011: {
    synopsis: "Após um evento catastrófico conhecido como \"O Flagelo\" ter dizimado grande parte da população mundial, bebês passaram a nascer como \"híbridos\", metade humanos e metade animais. Sem saber se os híbridos são a causa ou a consequência do vírus, muitos humanos os caçam por medo. Gus é um menino híbrido de cervo de 10 anos que cresceu isolado em uma floresta protegida por seu pai. Após a morte do pai, Gus parte em uma jornada perigosa pelo país acompanhado por Jepperd, um solitário errante, em busca de sua mãe.",
    tags: ["Pós-apocalíptico", "Aventura", "Fantasia"],
    platform: "Netflix",
    rating: 4,
  },
  rec_005_012: {
    synopsis: "Ava Silva é uma jovem tetraplégica de 19 anos que faleceu em um órfão corrupto na Espanha. Seu corpo é levado para uma igreja onde a Ordem da Espada Cruciforme — uma sociedade secreta de freiras caçadoras de demônios — está sob ataque. Para proteger o artefato sagrado conhecido como \"A Auréola\", uma das freiras o insere nas costas de Ava. A jovem não apenas ressuscita com saúde plena e superpoderes, mas descobre que agora é a nova Freira Guerreira escolhida para liderar a batalha contra forças demoníacas na Terra.",
    tags: ["Ação", "Fantasia", "Sobrenatural", "Religioso"],
    platform: "Netflix",
    rating: 3.5,
  },
  rec_006_001: {
    synopsis: "Após os eventos devastadores de Vingadores: Guerra Infinita, onde Thanos usou as seis Joias do Infinito para dizimar metade de toda a vida no universo, os heróis sobreviventes estão despedaçados e sem esperanças. Cinco anos depois, o retorno de Scott Lang do Reino Quântico revela a possibilidade técnica de realizar viagens no tempo. Os Vingadores remanescentes se reunificam para executar o \"Assalto no Tempo\", coletando as Joias no passado para reverter o estalo e enfrentar Thanos em uma batalha épica pela existência.",
    tags: ["Ação", "Super-heróis", "Sci-Fi", "Marvel"],
    platform: "Disney+",
    rating: 4,
  }
}