import type { Work } from "./types";
import type { PostedRecommendation } from "./communityStore";
import type { RelatedWork } from "./formConfig";
export interface RecommendationItem {
  id: string;
  type: string;
  title: string;
  author: string;
  synopsis: string;
  year: number;
  status: string;
  genres: string[];
  popularity: number;
  recommendedBy?: string; // @username de quem adicionou à biblioteca
  cover?: string; // capa da obra
  rating?: number; // avaliação (0-5) de quem publicou
  notes?: string; // comentário / nota pessoal de quem publicou
  link?: string;
  studio?: string;
  tags?: string[];
  reactions?: string[];
  // campos opcionais por tipo
  episodes?: number;
  chapters?: number;
  volumes?: number;
  issues?: number;
  pages?: number;
  duration?: number;
  hours?: number;
  seasons?: number;
  platform?: string;
  fandom?: string;
  words?: number;
  related?: RelatedWork[]; // obras relacionadas escolhidas manualmente pelo autor da obra
}
export const CATALOG: RecommendationItem[] = [
  // ── Anime ──────────────────────────────────────────────────────────────────
  {
    id: "rec_001_001",
    type: "Anime",
    title: "My Hero Academia",
    author: "Kohei Horikoshi",
    synopsis:
      "Em um mundo onde 80% da população possui superpoderes chamados 'Quirks', um garoto sem poderes chamado Izuku Midoriya sonha em se tornar um herói.",
    year: 2016,
    episodes: 138,
    status: "Em andamento",
    genres: ["Action", "Superhero", "School"],
    popularity: 95,
  },
  {
    id: "rec_001_002",
    type: "Anime",
    title: "Demon Slayer",
    author: "Koyoharu Gotouge",
    synopsis:
      "Tanjiro Kamado tem sua família massacrada por demônios. Sua irmã Nezuko é transformada em um demônio e ele se junta aos Caçadores de Demônios para encontrar uma cura.",
    year: 2019,
    episodes: 55,
    status: "Em andamento",
    genres: ["Action", "Dark Fantasy", "Historical"],
    popularity: 97,
  },
  {
    id: "rec_001_003",
    type: "Anime",
    title: "One Piece",
    author: "Eiichiro Oda",
    synopsis:
      "Monkey D. Luffy sonha em se tornar o Rei dos Piratas e viaja pelos mares em busca do tesouro lendário One Piece.",
    year: 1999,
    episodes: 1090,
    status: "Em andamento",
    genres: ["Action", "Adventure", "Comedy", "Fantasy"],
    popularity: 98,
  },
  {
    id: "rec_001_004",
    type: "Anime",
    title: "Bungo Stray Dogs",
    author: "Kafka Asagiri",
    synopsis:
      "Atsushi Nakajima se junta à Agência de Detetives Armados, um grupo de pessoas com habilidades sobrenaturais que enfrenta organizações criminosas.",
    year: 2016,
    episodes: 60,
    status: "Concluído",
    genres: ["Action", "Mystery", "Supernatural"],
    popularity: 85,
  },
  {
    id: "rec_001_005",
    type: "Anime",
    title: "Kuroko no Basuke",
    author: "Tadatoshi Fujimaki",
    synopsis:
      "A equipe de basquete da Seirin High School compete contra a chamada 'Geração dos Milagres'.",
    year: 2012,
    episodes: 75,
    status: "Concluído",
    genres: ["Sports", "School", "Comedy"],
    popularity: 82,
  },
  {
    id: "rec_001_006",
    type: "Anime",
    title: "Welcome to Demon School! Iruma-kun",
    author: "Osamu Nishi",
    synopsis:
      "Iruma Suzuki é vendido por seus pais a um demônio e vai para a escola de demônios, onde precisa esconder que é humano.",
    year: 2019,
    episodes: 65,
    status: "Em andamento",
    genres: ["Comedy", "Fantasy", "School"],
    popularity: 78,
  },
  {
    id: "rec_001_007",
    type: "Anime",
    title: "Gachiakuta",
    author: "Kei Urana",
    synopsis:
      "Rudo é acusado de um crime que não cometeu e jogado no Abismo, onde descobre um poder especial.",
    year: 2025,
    episodes: 12,
    status: "Concluído",
    genres: ["Action", "Supernatural", "Post-Apocalyptic"],
    popularity: 75,
  },
  {
    id: "rec_001_008",
    type: "Anime",
    title: "Jujutsu Kaisen",
    author: "Gege Akutami",
    synopsis:
      "Yuji Itadori engole um dedo amaldiçoado e se torna hospedeiro de Sukuna, juntando-se à Escola de Jujutsu.",
    year: 2020,
    episodes: 47,
    status: "Em andamento",
    genres: ["Action", "Supernatural", "Dark Fantasy"],
    popularity: 96,
  },
  {
    id: "rec_001_009",
    type: "Anime",
    title: "Wind Breaker",
    author: "Satoru Nii",
    synopsis: "Haruka Sakura entra na Furin High School e encontra um grupo que protege a cidade.",
    year: 2024,
    episodes: 13,
    status: "Concluído",
    genres: ["Action", "School", "Delinquent"],
    popularity: 80,
  },
  {
    id: "rec_001_010",
    type: "Anime",
    title: "Black Clover",
    author: "Yūki Tabata",
    synopsis:
      "Asta não tem poderes mágicos mas compete para se tornar o Rei Mago do Reino de Clover.",
    year: 2017,
    episodes: 170,
    status: "Concluído",
    genres: ["Action", "Adventure", "Fantasy"],
    popularity: 87,
  },
  {
    id: "rec_001_011",
    type: "Anime",
    title: "Solo Leveling",
    author: "Chugong",
    synopsis:
      "Sung Jin-Woo, o caçador mais fraco, adquire um sistema de level up e se torna o caçador mais poderoso.",
    year: 2024,
    episodes: 12,
    status: "Em andamento",
    genres: ["Action", "Fantasy", "Dungeon"],
    popularity: 94,
  },
  {
    id: "rec_001_012",
    type: "Anime",
    title: "Naruto",
    author: "Masashi Kishimoto",
    synopsis:
      "Naruto Uzumaki sonha em se tornar o Hokage e enfrenta inimigos poderosos em busca de reconhecimento.",
    year: 2002,
    episodes: 720,
    status: "Concluído",
    genres: ["Action", "Adventure", "Martial Arts"],
    popularity: 96,
  },
  {
    id: "rec_001_013",
    type: "Anime",
    title: "Fire Force",
    author: "Atsushi Ōkubo",
    synopsis:
      "Shinra Kusakabe se junta à Brigada de Combate a Incêndios Especial para descobrir a verdade sobre sua família.",
    year: 2019,
    episodes: 48,
    status: "Concluído",
    genres: ["Action", "Supernatural", "Sci-Fi"],
    popularity: 80,
  },
  {
    id: "rec_001_014",
    type: "Anime",
    title: "Soul Eater",
    author: "Atsushi Ōkubo",
    synopsis: "Maka e seu parceiro Soul caçam almas malignas na Academia Shibusen.",
    year: 2008,
    episodes: 51,
    status: "Concluído",
    genres: ["Action", "Supernatural", "Comedy"],
    popularity: 79,
  },
  {
    id: "rec_001_015",
    type: "Anime",
    title: "Tougen Anki",
    author: "Yura Urushibara",
    synopsis:
      "Shiki Ichinose descobre que é descendente de demônios e humanos e enfrenta conflitos entre as duas raças.",
    year: 2025,
    episodes: 12,
    status: "Concluído",
    genres: ["Action", "Supernatural", "School"],
    popularity: 70,
  },
  {
    id: "rec_001_016",
    type: "Anime",
    title: "Tensei Shitara Slime Datta Ken",
    author: "Fuse",
    synopsis:
      "Um homem reencarna como slime em um mundo de fantasia e constrói um reino onde monstros e humanos coexistem.",
    year: 2018,
    episodes: 72,
    status: "Em andamento",
    genres: ["Isekai", "Fantasy", "Adventure"],
    popularity: 88,
  },
  {
    id: "rec_001_017",
    type: "Anime",
    title: "Witch Hat Atelier",
    author: "Kamome Shirahama",
    synopsis: "Coco descobre que a magia é acessível a todos e se torna aprendiz de uma bruxa.",
    year: 2025,
    episodes: 12,
    status: "Concluído",
    genres: ["Fantasy", "Adventure", "Slice of Life"],
    popularity: 76,
  },
  {
    id: "rec_001_018",
    type: "Anime",
    title: "O Diário de uma Apotecária",
    author: "Natsu Hyuuga",
    synopsis:
      "Maomao usa sua inteligência em medicina para resolver mistérios e sobreviver no harém imperial.",
    year: 2023,
    episodes: 24,
    status: "Em andamento",
    genres: ["Mystery", "Historical", "Drama"],
    popularity: 84,
  },
  {
    id: "rec_001_019",
    type: "Anime",
    title: "Assassination Classroom",
    author: "Yūsei Matsui",
    synopsis:
      "Uma criatura alienígena se torna professor e os alunos devem matá-lo antes do fim do ano.",
    year: 2015,
    episodes: 47,
    status: "Concluído",
    genres: ["Action", "Comedy", "School"],
    popularity: 81,
  },
  {
    id: "rec_001_020",
    type: "Anime",
    title: "The Fragrant Flower Blooms with Dignity",
    author: "Saka Mikami",
    synopsis: "Romance entre dois estudantes de escolas rivais que se encontram secretamente.",
    year: 2025,
    episodes: 13,
    status: "Concluído",
    genres: ["Romance", "School", "Drama"],
    popularity: 72,
  },
  {
    id: "rec_001_021",
    type: "Anime",
    title: "Attack on Titan",
    author: "Hajime Isayama",
    synopsis:
      "Eren Yeager jura exterminar todos os titãs após eles destruírem sua cidade e matarem sua mãe.",
    year: 2013,
    episodes: 88,
    status: "Concluído",
    genres: ["Action", "Dark Fantasy", "Drama"],
    popularity: 97,
  },
  {
    id: "rec_001_022",
    type: "Anime",
    title: "Clevatess",
    author: "Yuji Iwahara",
    synopsis:
      "Uma família de aventureiros encontra a lendária espada Clevatess e embarca em uma jornada para salvar a humanidade.",
    year: 2024,
    episodes: 12,
    status: "Concluído",
    genres: ["Action", "Fantasy", "Adventure"],
    popularity: 65,
  },
  {
    id: "rec_001_023",
    type: "Anime",
    title: "The Water Magician",
    author: "Kouki Saito",
    synopsis: "Ryo descobre que é um mago da água e decide se tornar o mago mais poderoso.",
    year: 2024,
    episodes: 12,
    status: "Concluído",
    genres: ["Fantasy", "Adventure", "Magic"],
    popularity: 68,
  },
  {
    id: "rec_001_024",
    type: "Anime",
    title: "O Verão que Hikaru Morreu",
    author: "Mokumoku Ren",
    synopsis:
      "Yoshiki questiona a identidade de seu melhor amigo após ele retornar alterado das montanhas.",
    year: 2025,
    episodes: 12,
    status: "Concluído",
    genres: ["Mystery", "Supernatural", "Horror"],
    popularity: 69,
  },

  // ── Manga ──────────────────────────────────────────────────────────────────
  {
    id: "rec_002_001",
    type: "Manga",
    title: "One Punch Man",
    author: "One",
    synopsis:
      "Saitama pode derrotar qualquer inimigo com um soco e luta contra o tédio enquanto busca reconhecimento.",
    year: 2012,
    chapters: 200,
    status: "Em andamento",
    genres: ["Shonen", "Comedy", "Action"],
    popularity: 94,
  },
  {
    id: "rec_002_002",
    type: "Manga",
    title: "Dandadan",
    author: "Yukinobu Tatsu",
    synopsis:
      "Momo e Ken se envolvem em uma aventura sobrenatural quando descobrem que fantasmas e aliens existem.",
    year: 2021,
    chapters: 160,
    status: "Em andamento",
    genres: ["Shonen", "Supernatural", "Comedy"],
    popularity: 88,
  },
  {
    id: "rec_002_003",
    type: "Manga",
    title: "One Piece",
    author: "Eiichiro Oda",
    synopsis: "Monkey D. Luffy viaja pelos mares em busca do lendário tesouro One Piece.",
    year: 1997,
    chapters: 1100,
    status: "Em andamento",
    genres: ["Shonen", "Adventure", "Action"],
    popularity: 98,
  },
  {
    id: "rec_002_004",
    type: "Manga",
    title: "Tokyo Revengers",
    author: "Ken Wakui",
    synopsis:
      "Takemichi viaja no tempo para salvar sua ex-namorada e se envolve com gangues de motoqueiros.",
    year: 2017,
    chapters: 278,
    status: "Concluído",
    genres: ["Shonen", "Action", "Drama"],
    popularity: 85,
  },
  {
    id: "rec_002_005",
    type: "Manga",
    title: "Kimetsu no Yaiba",
    author: "Koyoharu Gotouge",
    synopsis:
      "Tanjiro se torna um Caçador de Demônios para encontrar uma cura para sua irmã Nezuko.",
    year: 2016,
    chapters: 205,
    status: "Concluído",
    genres: ["Shonen", "Action", "Fantasy"],
    popularity: 96,
  },
  {
    id: "rec_002_006",
    type: "Manga",
    title: "Kaiju No. 8",
    author: "Naoya Matsumoto",
    synopsis:
      "Kafka Hibino se transforma em um kaiju e se junta à Força de Defesa para proteger a humanidade.",
    year: 2020,
    chapters: 110,
    status: "Em andamento",
    genres: ["Shonen", "Action", "Sci-Fi"],
    popularity: 87,
  },
  {
    id: "rec_002_007",
    type: "Manga",
    title: "Black Clover",
    author: "Yūki Tabata",
    synopsis: "Asta, um garoto sem magia, compete para se tornar o Rei Mago.",
    year: 2015,
    chapters: 370,
    status: "Em andamento",
    genres: ["Shonen", "Action", "Fantasy"],
    popularity: 86,
  },
  {
    id: "rec_002_008",
    type: "Manga",
    title: "My Hero Academia",
    author: "Kohei Horikoshi",
    synopsis: "Izuku Midoriya herda o poder de All Might e treina para se tornar um herói.",
    year: 2014,
    chapters: 430,
    status: "Em andamento",
    genres: ["Shonen", "Action", "Superhero"],
    popularity: 95,
  },
  {
    id: "rec_002_009",
    type: "Manga",
    title: "Spy x Family",
    author: "Tatsuya Endo",
    synopsis:
      "Um espião, uma assassina e uma garota psíquica formam uma família falsa sem saberem os segredos uns dos outros.",
    year: 2019,
    chapters: 100,
    status: "Em andamento",
    genres: ["Shonen", "Comedy", "Action"],
    popularity: 92,
  },
  {
    id: "rec_002_010",
    type: "Manga",
    title: "Chainsaw Man",
    author: "Tatsuki Fujimoto",
    synopsis: "Denji se funde com seu demônio de estimação e se torna Chainsaw Man.",
    year: 2018,
    chapters: 180,
    status: "Em andamento",
    genres: ["Shonen", "Action", "Horror"],
    popularity: 94,
  },
  {
    id: "rec_002_011",
    type: "Manga",
    title: "Jujutsu Kaisen",
    author: "Gege Akutami",
    synopsis: "Yuji Itadori se torna hospedeiro da maldição Sukuna e combate maldições.",
    year: 2018,
    chapters: 270,
    status: "Em andamento",
    genres: ["Shonen", "Action", "Supernatural"],
    popularity: 97,
  },
  {
    id: "rec_002_012",
    type: "Manga",
    title: "Gachiakuta",
    author: "Kei Urana",
    synopsis: "Rudo é jogado no Abismo e descobre um poder especial.",
    year: 2022,
    chapters: 120,
    status: "Em andamento",
    genres: ["Shonen", "Action", "Supernatural"],
    popularity: 78,
  },
  {
    id: "rec_002_013",
    type: "Manga",
    title: "Attack on Titan",
    author: "Hajime Isayama",
    synopsis: "Eren Yeager jura exterminar todos os titãs.",
    year: 2009,
    chapters: 139,
    status: "Concluído",
    genres: ["Shonen", "Action", "Dark Fantasy"],
    popularity: 96,
  },

  // ── Manhwa ─────────────────────────────────────────────────────────────────
  {
    id: "rec_003_001",
    type: "Manhwa",
    title: "Solo Leveling",
    author: "Chugong",
    synopsis:
      "Sung Jin-Woo adquire um sistema de level up e se torna o caçador mais poderoso do mundo.",
    year: 2018,
    chapters: 179,
    status: "Concluído",
    genres: ["Fantasy", "Action", "Dungeon"],
    popularity: 97,
  },
  {
    id: "rec_003_002",
    type: "Manhwa",
    title: "Omniscient Reader's Viewpoint",
    author: "Sing Shong",
    synopsis:
      "Kim Dokja descobre que o mundo real se tornou a história que ele lia e usa seu conhecimento para sobreviver.",
    year: 2020,
    chapters: 230,
    status: "Em andamento",
    genres: ["Fantasy", "Action", "Apocalyptic"],
    popularity: 93,
  },
  {
    id: "rec_003_003",
    type: "Manhwa",
    title: "The Greatest Estate Developer",
    author: "BK Moon",
    synopsis:
      "Um engenheiro civil reencarna como nobre e usa seu conhecimento para construir o maior império imobiliário.",
    year: 2021,
    chapters: 150,
    status: "Em andamento",
    genres: ["Fantasy", "Comedy", "Adventure"],
    popularity: 86,
  },
  {
    id: "rec_003_004",
    type: "Manhwa",
    title: "The Beginning After the End",
    author: "TurtleMe",
    synopsis: "Um rei poderoso reencarna como bebê em um mundo de fantasia.",
    year: 2018,
    chapters: 190,
    status: "Em andamento",
    genres: ["Fantasy", "Action", "Adventure"],
    popularity: 90,
  },
  {
    id: "rec_003_005",
    type: "Manhwa",
    title: "Return of the Mount Hua Sect",
    author: "Biga",
    synopsis:
      "O lendário líder do Seita Mount Hua reencarna e tenta restaurar a glória de sua seita.",
    year: 2021,
    chapters: 160,
    status: "Em andamento",
    genres: ["Fantasy", "Action", "Martial Arts"],
    popularity: 85,
  },
  {
    id: "rec_003_006",
    type: "Manhwa",
    title: "Nano Machine",
    author: "Hanjung Wolya",
    synopsis:
      "Um descendente do clã Cheon recebe nano-máquinas do futuro que o ajudam a dominar as artes marciais.",
    year: 2020,
    chapters: 200,
    status: "Em andamento",
    genres: ["Fantasy", "Action", "Sci-Fi"],
    popularity: 87,
  },
  {
    id: "rec_003_007",
    type: "Manhwa",
    title: "SSS-Class Revival Hunter",
    author: "Neida",
    synopsis:
      "Um caçador de classe F ganha uma habilidade de renascimento e se torna o mais poderoso.",
    year: 2021,
    chapters: 150,
    status: "Em andamento",
    genres: ["Fantasy", "Action", "Adventure"],
    popularity: 83,
  },
  {
    id: "rec_003_008",
    type: "Manhwa",
    title: "A Returner's Magic Should Be Special",
    author: "Usonan",
    synopsis: "O mago mais poderoso retorna no tempo para evitar a destruição do mundo.",
    year: 2018,
    chapters: 240,
    status: "Em andamento",
    genres: ["Fantasy", "Action", "Magic"],
    popularity: 84,
  },
  {
    id: "rec_003_009",
    type: "Manhwa",
    title: "Doom Breaker",
    author: "Umjjang",
    synopsis: "O herói mais forte retorna no tempo para reverter o apocalipse.",
    year: 2021,
    chapters: 140,
    status: "Em andamento",
    genres: ["Fantasy", "Action", "Apocalyptic"],
    popularity: 82,
  },
  {
    id: "rec_003_010",
    type: "Manhwa",
    title: "Murim Login",
    author: "Jeong Ji Han",
    synopsis:
      "Um caçador de rank baixo descobre um dispositivo que o transporta para um mundo de artes marciais.",
    year: 2020,
    chapters: 180,
    status: "Em andamento",
    genres: ["Fantasy", "Action", "Martial Arts"],
    popularity: 84,
  },

  // ── Manhua ─────────────────────────────────────────────────────────────────
  {
    id: "rec_004_001",
    type: "Manhua",
    title: "Magic Emperor",
    author: "Xiao Long",
    synopsis: "Um imperador demoníaco reencarna como nobre desprezado e busca recuperar seu poder.",
    year: 2019,
    chapters: 450,
    status: "Em andamento",
    genres: ["Cultivation", "Fantasy", "Action"],
    popularity: 85,
  },
  {
    id: "rec_004_002",
    type: "Manhua",
    title: "Battle Through the Heavens",
    author: "Tian Can Tu Dou",
    synopsis: "Xiao Yan, um prodígio que perdeu seu poder, busca se vingar e recuperar sua força.",
    year: 2011,
    chapters: 800,
    status: "Em andamento",
    genres: ["Cultivation", "Fantasy", "Action"],
    popularity: 90,
  },
  {
    id: "rec_004_003",
    type: "Manhua",
    title: "Soul Land",
    author: "Tang Jia San Shao",
    synopsis:
      "Tang San reencarna em um mundo onde humanos cultivam almas e busca se tornar o mais poderoso.",
    year: 2011,
    chapters: 500,
    status: "Em andamento",
    genres: ["Cultivation", "Fantasy", "Action"],
    popularity: 89,
  },
  {
    id: "rec_004_004",
    type: "Manhua",
    title: "Tales of Demons and Gods",
    author: "Mad Snail",
    synopsis:
      "Nie Li, um dos cultivadores mais poderosos, reencarna como jovem para proteger sua cidade.",
    year: 2015,
    chapters: 450,
    status: "Em andamento",
    genres: ["Cultivation", "Fantasy", "Action"],
    popularity: 86,
  },
  {
    id: "rec_004_005",
    type: "Manhua",
    title: "Martial Peak",
    author: "Momo",
    synopsis:
      "Yang Kai descobre segredos que o levam a se tornar um dos cultivadores mais poderosos do universo.",
    year: 2015,
    chapters: 3000,
    status: "Em andamento",
    genres: ["Cultivation", "Fantasy", "Action"],
    popularity: 88,
  },
  {
    id: "rec_004_006",
    type: "Manhua",
    title: "I Am the Fated Villain",
    author: "Dao",
    synopsis:
      "Um jovem que deveria ser o vilão decide mudar seu destino usando seu conhecimento do enredo original.",
    year: 2021,
    chapters: 280,
    status: "Em andamento",
    genres: ["Cultivation", "Fantasy", "Action"],
    popularity: 78,
  },

  // ── Série ──────────────────────────────────────────────────────────────────
  {
    id: "rec_005_001",
    type: "Série",
    title: "La Casa de Papel",
    author: "Álex Pina",
    synopsis:
      "O Professor planeja o maior assalto da história, invadindo a Casa da Moeda da Espanha.",
    year: 2017,
    episodes: 41,
    seasons: 5,
    status: "Concluído",
    genres: ["Drama", "Thriller", "Crime"],
    popularity: 94,
  },
  {
    id: "rec_005_002",
    type: "Série",
    title: "The Amazing Digital Circus",
    author: "Gooseworx",
    synopsis:
      "Um grupo de humanos fica preso em um jogo de circo digital e tenta manter a sanidade.",
    year: 2023,
    episodes: 9,
    seasons: 1,
    status: "Em andamento",
    genres: ["Drama", "Comedy", "Psychological"],
    popularity: 86,
  },
  {
    id: "rec_005_003",
    type: "Série",
    title: "The Flash",
    author: "Greg Berlanti",
    synopsis: "Barry Allen ganha supervelocidade e se torna o Flash, protegendo Central City.",
    year: 2014,
    episodes: 184,
    seasons: 9,
    status: "Concluído",
    genres: ["Drama", "Action", "Superhero"],
    popularity: 88,
  },
  {
    id: "rec_005_004",
    type: "Série",
    title: "Atypical",
    author: "Robia Rashid",
    synopsis:
      "Sam, um jovem autista, decide encontrar um par e enfrenta os desafios do amor e da independência.",
    year: 2017,
    episodes: 38,
    seasons: 4,
    status: "Concluído",
    genres: ["Drama", "Comedy", "Romance"],
    popularity: 83,
  },
  {
    id: "rec_005_005",
    type: "Série",
    title: "Arcane",
    author: "Christian Linke",
    synopsis: "Em Piltover e Zaun, duas irmãs se envolvem em um conflito entre magia e tecnologia.",
    year: 2021,
    episodes: 18,
    seasons: 2,
    status: "Em andamento",
    genres: ["Drama", "Action", "Fantasy"],
    popularity: 95,
  },
  {
    id: "rec_005_006",
    type: "Série",
    title: "The Umbrella Academy",
    author: "Steve Blackman",
    synopsis:
      "Sete irmãos com superpoderes se reúnem para investigar a morte do pai e impedir o apocalipse.",
    year: 2019,
    episodes: 36,
    seasons: 4,
    status: "Concluído",
    genres: ["Drama", "Action", "Superhero"],
    popularity: 90,
  },
  {
    id: "rec_005_007",
    type: "Série",
    title: "Alice in Borderland",
    author: "Yoshiki Watabe",
    synopsis: "Um grupo de amigos precisa participar de jogos mortais em uma Tóquio vazia.",
    year: 2020,
    episodes: 16,
    seasons: 2,
    status: "Concluído",
    genres: ["Drama", "Thriller", "Sci-Fi"],
    popularity: 89,
  },
  {
    id: "rec_005_008",
    type: "Série",
    title: "Round 6 (Squid Game)",
    author: "Hwang Dong-hyuk",
    synopsis:
      "Pessoas em situação desesperada participam de jogos infantis onde perder significa morte.",
    year: 2021,
    episodes: 9,
    seasons: 1,
    status: "Concluído",
    genres: ["Drama", "Thriller", "Survival"],
    popularity: 96,
  },
  {
    id: "rec_005_009",
    type: "Série",
    title: "Manifest",
    author: "Jeff Rake",
    synopsis:
      "Um avião desaparece e retorna cinco anos depois com passageiros sem envelhecer e com visões misteriosas.",
    year: 2018,
    episodes: 62,
    seasons: 4,
    status: "Concluído",
    genres: ["Drama", "Sci-Fi", "Mystery"],
    popularity: 84,
  },
  {
    id: "rec_005_010",
    type: "Série",
    title: "Heartstopper",
    author: "Alice Oseman",
    synopsis:
      "Charlie e Nick desenvolvem uma amizade que se transforma em amor enquanto enfrentam desafios da adolescência.",
    year: 2022,
    episodes: 16,
    seasons: 2,
    status: "Em andamento",
    genres: ["Drama", "Romance", "Comedy"],
    popularity: 91,
  },
  {
    id: "rec_005_011",
    type: "Série",
    title: "Sweet Tooth",
    author: "Jim Mickle",
    synopsis:
      "Em um mundo pós-apocalíptico, um menino meio humano meio veado sai em busca de um novo lar.",
    year: 2021,
    episodes: 16,
    seasons: 2,
    status: "Concluído",
    genres: ["Drama", "Fantasy", "Adventure"],
    popularity: 79,
  },
  {
    id: "rec_005_012",
    type: "Série",
    title: "Warrior Nun",
    author: "Simon Barry",
    synopsis:
      "Uma jovem acorda com um artefato divino nas costas e descobre que agora é uma guerreira contra demônios.",
    year: 2020,
    episodes: 18,
    seasons: 2,
    status: "Concluído",
    genres: ["Drama", "Fantasy", "Action"],
    popularity: 77,
  },

  // ── Filme ──────────────────────────────────────────────────────────────────
  {
    id: "rec_006_001",
    type: "Filme",
    title: "Avengers: Endgame",
    author: "Anthony e Joe Russo",
    synopsis: "Os Vingadores viajam no tempo para desfazer o estalo de Thanos.",
    year: 2019,
    duration: 181,
    status: "Concluído",
    genres: ["Action", "Sci-Fi", "Superhero"],
    popularity: 96,
  },
  {
    id: "rec_006_002",
    type: "Filme",
    title: "The Dark Knight",
    author: "Christopher Nolan",
    synopsis: "Batman enfrenta o Coringa em Gotham City, questionando seus limites e moralidade.",
    year: 2008,
    duration: 152,
    status: "Concluído",
    genres: ["Action", "Crime", "Drama"],
    popularity: 95,
  },
  {
    id: "rec_006_003",
    type: "Filme",
    title: "Interstellar",
    author: "Christopher Nolan",
    synopsis:
      "Uma equipe de exploradores viaja por um buraco de minhoca para encontrar um novo lar para a humanidade.",
    year: 2014,
    duration: 169,
    status: "Concluído",
    genres: ["Sci-Fi", "Drama", "Adventure"],
    popularity: 93,
  },
  {
    id: "rec_006_004",
    type: "Filme",
    title: "Inception",
    author: "Christopher Nolan",
    synopsis:
      "Um ladrão especializado em roubar segredos dos sonhos recebe a missão de plantar uma ideia.",
    year: 2010,
    duration: 148,
    status: "Concluído",
    genres: ["Sci-Fi", "Action", "Thriller"],
    popularity: 92,
  },
  {
    id: "rec_006_005",
    type: "Filme",
    title: "Spider-Man: No Way Home",
    author: "Jon Watts",
    synopsis: "Peter Parker abre o multiverso, trazendo vilões de outras realidades.",
    year: 2021,
    duration: 148,
    status: "Concluído",
    genres: ["Action", "Adventure", "Superhero"],
    popularity: 94,
  },
  {
    id: "rec_006_006",
    type: "Filme",
    title: "Dune: Part Two",
    author: "Denis Villeneuve",
    synopsis: "Paul Atreides lidera os Fremen em uma guerra contra os Harkonnen e o Imperador.",
    year: 2024,
    duration: 166,
    status: "Concluído",
    genres: ["Sci-Fi", "Action", "Adventure"],
    popularity: 90,
  },
  {
    id: "rec_006_007",
    type: "Filme",
    title: "Everything Everywhere All at Once",
    author: "Daniel Kwan e Daniel Scheinert",
    synopsis: "Uma imigrante chinesa pode acessar outros universos e precisa salvar sua família.",
    year: 2022,
    duration: 139,
    status: "Concluído",
    genres: ["Sci-Fi", "Comedy", "Action"],
    popularity: 86,
  },
  {
    id: "rec_006_008",
    type: "Filme",
    title: "Parasite",
    author: "Bong Joon-ho",
    synopsis:
      "Uma família pobre se infiltra na vida de uma família rica, mas segredos sombrios vêm à tona.",
    year: 2019,
    duration: 132,
    status: "Concluído",
    genres: ["Drama", "Thriller", "Comedy"],
    popularity: 91,
  },
  {
    id: "rec_006_009",
    type: "Filme",
    title: "Oppenheimer",
    author: "Christopher Nolan",
    synopsis: "A história de Oppenheimer e seu papel no desenvolvimento da bomba atômica.",
    year: 2023,
    duration: 180,
    status: "Concluído",
    genres: ["Drama", "Historical", "Thriller"],
    popularity: 89,
  },
  {
    id: "rec_006_010",
    type: "Filme",
    title: "The Lord of the Rings: The Return of the King",
    author: "Peter Jackson",
    synopsis:
      "A conclusão épica da trilogia, onde Frodo e Sam continuam a jornada para destruir o Um Anel.",
    year: 2003,
    duration: 201,
    status: "Concluído",
    genres: ["Fantasy", "Adventure", "Action"],
    popularity: 96,
  },
  {
    id: "rec_006_011",
    type: "Filme",
    title: "Deadpool & Wolverine",
    author: "Shawn Levy",
    synopsis: "Deadpool e Wolverine se unem em uma aventura caótica pelo multiverso.",
    year: 2024,
    duration: 128,
    status: "Concluído",
    genres: ["Action", "Comedy", "Superhero"],
    popularity: 91,
  },
  {
    id: "rec_006_012",
    type: "Filme",
    title: "Inside Out 2",
    author: "Kelsey Mann",
    synopsis:
      "Riley vira adolescente e novas emoções chegam ao Quartel General, desafiando a Alegria.",
    year: 2024,
    duration: 100,
    status: "Concluído",
    genres: ["Animation", "Comedy", "Family"],
    popularity: 87,
  },

  // ── Jogo ───────────────────────────────────────────────────────────────────
  {
    id: "rec_007_001",
    type: "Jogo",
    title: "The Last of Us",
    author: "Naughty Dog",
    synopsis: "Joel e Ellie viajam pelos EUA pós-apocalípticos em uma jornada perigosa.",
    year: 2013,
    hours: 30,
    platform: "PS5 / PC",
    status: "Concluído",
    genres: ["Action", "Adventure", "Survival"],
    popularity: 96,
  },
  {
    id: "rec_007_002",
    type: "Jogo",
    title: "Hogwarts Legacy",
    author: "Avalanche Software",
    synopsis: "Um RPG de mundo aberto em Hogwarts onde você vive suas próprias aventuras.",
    year: 2023,
    hours: 45,
    platform: "PS5 / Xbox / PC",
    status: "Concluído",
    genres: ["RPG", "Open World", "Fantasy"],
    popularity: 88,
  },
  {
    id: "rec_007_003",
    type: "Jogo",
    title: "Cyberpunk 2077",
    author: "CD Projekt Red",
    synopsis: "V, um mercenário, busca imortalidade em Night City.",
    year: 2020,
    hours: 70,
    platform: "PS5 / Xbox / PC",
    status: "Concluído",
    genres: ["RPG", "Open World", "Sci-Fi"],
    popularity: 86,
  },
  {
    id: "rec_007_004",
    type: "Jogo",
    title: "Stray",
    author: "BlueTwelve Studio",
    synopsis: "Um gato explora uma cidade cibernética, resolvendo enigmas e evitando perigos.",
    year: 2022,
    hours: 8,
    platform: "PC / PS5",
    status: "Concluído",
    genres: ["Adventure", "Puzzle", "Indie"],
    popularity: 86,
  },
  {
    id: "rec_007_005",
    type: "Jogo",
    title: "Life is Strange",
    author: "Dontnod Entertainment",
    synopsis: "Série episódica com narrativas emocionais onde as escolhas afetam o desfecho.",
    year: 2015,
    hours: 40,
    platform: "PC / PS5 / Xbox",
    status: "Concluído",
    genres: ["Adventure", "Drama", "Choice-Driven"],
    popularity: 85,
  },
  {
    id: "rec_007_006",
    type: "Jogo",
    title: "Cult of the Lamb",
    author: "Massive Monster",
    synopsis: "Um cordeiro lidera um culto, construindo uma comunidade enquanto explora masmorras.",
    year: 2022,
    hours: 25,
    platform: "PC / PS5 / Switch",
    status: "Concluído",
    genres: ["Roguelike", "Simulation", "Adventure"],
    popularity: 84,
  },
  {
    id: "rec_007_007",
    type: "Jogo",
    title: "Little Nightmares",
    author: "Tarsier Studios",
    synopsis: "Six tenta escapar de um navio cheio de criaturas monstruosas.",
    year: 2017,
    hours: 6,
    platform: "PC / PS5 / Switch",
    status: "Concluído",
    genres: ["Horror", "Platformer", "Puzzle"],
    popularity: 81,
  },
  {
    id: "rec_007_008",
    type: "Jogo",
    title: "Terraria",
    author: "Re-Logic",
    synopsis:
      "Um sandbox 2D onde você explora, constrói e luta em um mundo gerado proceduralmente.",
    year: 2011,
    hours: 100,
    platform: "PC / PS5 / Switch",
    status: "Concluído",
    genres: ["Sandbox", "Adventure", "Action"],
    popularity: 89,
  },
  {
    id: "rec_007_009",
    type: "Jogo",
    title: "Minecraft",
    author: "Mojang Studios",
    synopsis: "Construa e explore mundos infinitos de blocos com modos criativo e sobrevivência.",
    year: 2011,
    hours: 200,
    platform: "PC / PS5 / Xbox / Switch",
    status: "Em andamento",
    genres: ["Sandbox", "Adventure", "Survival"],
    popularity: 98,
  },
  {
    id: "rec_007_010",
    type: "Jogo",
    title: "GTA 5",
    author: "Rockstar Games",
    synopsis: "Três criminosos se unem para realizar assaltos e sobreviver em Los Santos.",
    year: 2013,
    hours: 80,
    platform: "PS5 / Xbox / PC",
    status: "Concluído",
    genres: ["Action", "Open World", "Crime"],
    popularity: 95,
  },

  // ── Livro ──────────────────────────────────────────────────────────────────
  {
    id: "rec_008_001",
    type: "Livro",
    title: "Harry Potter e a Pedra Filosofal",
    author: "J.K. Rowling",
    synopsis: "Harry Potter descobre que é um bruxo e enfrenta um perigo escondido em Hogwarts.",
    year: 1997,
    pages: 223,
    status: "Concluído",
    genres: ["Fantasy", "Adventure", "Magic"],
    popularity: 97,
  },
  {
    id: "rec_008_002",
    type: "Livro",
    title: "O Senhor dos Anéis: A Sociedade do Anel",
    author: "J.R.R. Tolkien",
    synopsis: "Frodo deve destruir o Um Anel antes que Sauron o recupere.",
    year: 1954,
    pages: 423,
    status: "Concluído",
    genres: ["Fantasy", "Adventure", "Epic"],
    popularity: 96,
  },
  {
    id: "rec_008_003",
    type: "Livro",
    title: "Percy Jackson e o Ladrão de Raios",
    author: "Rick Riordan",
    synopsis: "Percy Jackson descobre que é um semideus e busca o raio de Zeus.",
    year: 2005,
    pages: 377,
    status: "Concluído",
    genres: ["Fantasy", "Adventure", "Mythology"],
    popularity: 89,
  },
  {
    id: "rec_008_004",
    type: "Livro",
    title: "Jogos Vorazes",
    author: "Suzanne Collins",
    synopsis: "Katniss se voluntaria nos Jogos Vorazes para salvar sua irmã.",
    year: 2008,
    pages: 374,
    status: "Concluído",
    genres: ["Sci-Fi", "Dystopian", "Action"],
    popularity: 93,
  },
  {
    id: "rec_008_005",
    type: "Livro",
    title: "1984",
    author: "George Orwell",
    synopsis: "Winston Smith luta contra o regime totalitário do Grande Irmão.",
    year: 1949,
    pages: 328,
    status: "Concluído",
    genres: ["Sci-Fi", "Dystopian", "Political"],
    popularity: 95,
  },
  {
    id: "rec_008_006",
    type: "Livro",
    title: "Duna",
    author: "Frank Herbert",
    synopsis:
      "Paul Atreides luta pelo controle do planeta Arrakis, onde a especiaria mais valiosa do universo é encontrada.",
    year: 1965,
    pages: 412,
    status: "Concluído",
    genres: ["Sci-Fi", "Epic", "Adventure"],
    popularity: 92,
  },
  {
    id: "rec_008_007",
    type: "Livro",
    title: "A Culpa é das Estrelas",
    author: "John Green",
    synopsis:
      "Hazel Grace, com câncer, se apaixona por Augustus Waters em um romance sobre amor e mortalidade.",
    year: 2012,
    pages: 318,
    status: "Concluído",
    genres: ["Romance", "Drama", "Young Adult"],
    popularity: 89,
  },
  {
    id: "rec_008_008",
    type: "Livro",
    title: "O Alquimista",
    author: "Paulo Coelho",
    synopsis:
      "Santiago viaja em busca de seu sonho e descobre a importância de seguir sua lenda pessoal.",
    year: 1988,
    pages: 208,
    status: "Concluído",
    genres: ["Fantasy", "Philosophical", "Adventure"],
    popularity: 88,
  },
  {
    id: "rec_008_009",
    type: "Livro",
    title: "Verity",
    author: "Colleen Hoover",
    synopsis: "Uma escritora contratada para terminar uma série descobre segredos perturbadores.",
    year: 2018,
    pages: 323,
    status: "Concluído",
    genres: ["Thriller", "Mystery", "Romance"],
    popularity: 86,
  },
  {
    id: "rec_008_010",
    type: "Livro",
    title: "Dom Casmurro",
    author: "Machado de Assis",
    synopsis: "Bentinho narra sua vida e levanta a dúvida sobre a traição de sua amada Capitu.",
    year: 1899,
    pages: 260,
    status: "Concluído",
    genres: ["Drama", "Romance", "Classic"],
    popularity: 86,
  },

  // ── Light Novel ────────────────────────────────────────────────────────────
  {
    id: "rec_009_001",
    type: "Light Novel",
    title: "Sword Art Online",
    author: "Reki Kawahara",
    synopsis:
      "Jogadores ficam presos em um MMORPG onde a morte no jogo significa morte na vida real.",
    year: 2009,
    volumes: 27,
    status: "Em andamento",
    genres: ["Sci-Fi", "Action", "Virtual Reality"],
    popularity: 92,
  },
  {
    id: "rec_009_002",
    type: "Light Novel",
    title: "Re:Zero",
    author: "Tappei Nagatsuki",
    synopsis: "Subaru Natsuki pode voltar no tempo quando morre, tentando salvar aqueles que ama.",
    year: 2014,
    volumes: 35,
    status: "Em andamento",
    genres: ["Isekai", "Psychological", "Fantasy"],
    popularity: 90,
  },
  {
    id: "rec_009_003",
    type: "Light Novel",
    title: "Overlord",
    author: "Kugane Maruyama",
    synopsis: "Um jogador preso no MMORPG se torna um poderoso lich e busca dominar o novo mundo.",
    year: 2012,
    volumes: 16,
    status: "Em andamento",
    genres: ["Isekai", "Fantasy", "Dark"],
    popularity: 89,
  },
  {
    id: "rec_009_004",
    type: "Light Novel",
    title: "KonoSuba",
    author: "Natsume Akatsuki",
    synopsis: "Kazuma Satou forma um grupo disfuncional para derrotar o Rei Demônio.",
    year: 2013,
    volumes: 17,
    status: "Concluído",
    genres: ["Isekai", "Comedy", "Fantasy"],
    popularity: 89,
  },
  {
    id: "rec_009_005",
    type: "Light Novel",
    title: "A Sala de Aula da Elite",
    author: "Syougo Kinugasa",
    synopsis:
      "Em uma escola de elite, estudantes competem em um sistema implacável onde só os melhores sobrevivem.",
    year: 2015,
    volumes: 14,
    status: "Em andamento",
    genres: ["School", "Psychological", "Drama"],
    popularity: 86,
  },
  {
    id: "rec_009_006",
    type: "Light Novel",
    title: "The Eminence in Shadow",
    author: "Daisuke Aizawa",
    synopsis: "Um garoto cria uma organização secreta para combater um mal que não sabe se é real.",
    year: 2018,
    volumes: 6,
    status: "Em andamento",
    genres: ["Isekai", "Comedy", "Fantasy"],
    popularity: 87,
  },
  {
    id: "rec_009_007",
    type: "Light Novel",
    title: "86 - Oitenta e Seis",
    author: "Asato Asato",
    synopsis: "Os 86 são tratados como subumanos e lutam em uma guerra sem fim.",
    year: 2017,
    volumes: 13,
    status: "Em andamento",
    genres: ["Sci-Fi", "Drama", "War"],
    popularity: 83,
  },
  {
    id: "rec_009_008",
    type: "Light Novel",
    title: "No Game No Life",
    author: "Yuu Kamiya",
    synopsis: "Dois irmãos gamers são transportados para Disboard, onde tudo é decidido por jogos.",
    year: 2012,
    volumes: 12,
    status: "Em andamento",
    genres: ["Isekai", "Comedy", "Fantasy"],
    popularity: 85,
  },

  // ── Webtoon ────────────────────────────────────────────────────────────────
  {
    id: "rec_010_001",
    type: "Webtoon",
    title: "Tower of God",
    author: "SIU",
    synopsis: "Bam entra em uma torre misteriosa em busca de sua amiga Rachel.",
    year: 2010,
    chapters: 600,
    status: "Em andamento",
    genres: ["Fantasy", "Action", "Adventure"],
    popularity: 91,
  },
  {
    id: "rec_010_002",
    type: "Webtoon",
    title: "Lookism",
    author: "Park Tae-joon",
    synopsis:
      "Daniel descobre que pode mudar de corpo e vive duas vidas, explorando o preconceito e a beleza.",
    year: 2014,
    chapters: 500,
    status: "Em andamento",
    genres: ["Drama", "Action", "School"],
    popularity: 87,
  },
  {
    id: "rec_010_003",
    type: "Webtoon",
    title: "Sweet Home",
    author: "Carnby Kim",
    synopsis:
      "Pessoas se transformam em monstros com base em seus desejos e um grupo tenta sobreviver.",
    year: 2017,
    chapters: 140,
    status: "Concluído",
    genres: ["Horror", "Thriller", "Survival"],
    popularity: 88,
  },
  {
    id: "rec_010_004",
    type: "Webtoon",
    title: "Lore Olympus",
    author: "Rachel Smythe",
    synopsis: "Releitura moderna do mito de Hades e Perséfone com romance e intriga entre deuses.",
    year: 2018,
    chapters: 250,
    status: "Em andamento",
    genres: ["Romance", "Fantasy", "Mythology"],
    popularity: 89,
  },
  {
    id: "rec_010_005",
    type: "Webtoon",
    title: "True Beauty",
    author: "Yaongyi",
    synopsis:
      "Jugyeong descobre a maquiagem e passa a viver uma vida dupla, escondendo seu rosto real.",
    year: 2018,
    chapters: 250,
    status: "Em andamento",
    genres: ["Romance", "Comedy", "School"],
    popularity: 88,
  },
  {
    id: "rec_010_006",
    type: "Webtoon",
    title: "Omniscient Reader's Viewpoint",
    author: "Sing Shong",
    synopsis:
      "Kim Dokja usa seu conhecimento de uma webnovel para sobreviver em um mundo que se tornou a história.",
    year: 2020,
    chapters: 230,
    status: "Em andamento",
    genres: ["Fantasy", "Action", "Apocalyptic"],
    popularity: 93,
  },
  {
    id: "rec_010_007",
    type: "Webtoon",
    title: "UnOrdinary",
    author: "uru-chan",
    synopsis:
      "Em um mundo onde superpoderes definem o status social, um garoto sem poderes tenta sobreviver.",
    year: 2016,
    chapters: 300,
    status: "Em andamento",
    genres: ["Action", "School", "Drama"],
    popularity: 86,
  },

  // ── Donghua ────────────────────────────────────────────────────────────────
  {
    id: "rec_011_001",
    type: "Donghua",
    title: "Link Click",
    author: "Li Haoling",
    synopsis:
      "Cheng Xiaoshi e Lu Guang entram em fotos para influenciar o passado, mas com consequências perigosas.",
    year: 2021,
    episodes: 24,
    status: "Em andamento",
    genres: ["Supernatural", "Drama", "Mystery"],
    popularity: 86,
  },
  {
    id: "rec_011_002",
    type: "Donghua",
    title: "Grandmaster of Demonic Cultivation",
    author: "Mo Xiang Tong Xiu",
    synopsis: "Wei Wuxian reencarna e busca desvendar os mistérios de sua morte.",
    year: 2018,
    episodes: 23,
    status: "Concluído",
    genres: ["Cultivation", "Fantasy", "Mystery"],
    popularity: 89,
  },
  {
    id: "rec_011_003",
    type: "Donghua",
    title: "Heaven Official's Blessing",
    author: "Mo Xiang Tong Xiu",
    synopsis: "Xie Lian e Hua Cheng embarcam em uma jornada para resolver mistérios sobrenaturais.",
    year: 2020,
    episodes: 11,
    status: "Concluído",
    genres: ["Cultivation", "Fantasy", "Romance"],
    popularity: 87,
  },
  {
    id: "rec_011_004",
    type: "Donghua",
    title: "Soul Land",
    author: "Tang Jia San Shao",
    synopsis: "Tang San reencarna em um mundo de cultivação e busca se tornar o mais poderoso.",
    year: 2018,
    episodes: 260,
    status: "Em andamento",
    genres: ["Cultivation", "Fantasy", "Action"],
    popularity: 90,
  },
  {
    id: "rec_011_005",
    type: "Donghua",
    title: "The King's Avatar",
    author: "Hu Dielan",
    synopsis:
      "Ye Xiu, o lendário jogador de Glory, é forçado a se aposentar mas volta ao jogo como novato.",
    year: 2017,
    episodes: 12,
    status: "Concluído",
    genres: ["Action", "Sci-Fi", "Sports"],
    popularity: 86,
  },
  {
    id: "rec_011_006",
    type: "Donghua",
    title: "Lord of Mysteries",
    author: "Cuttlefish That Loves Diving",
    synopsis:
      "Klein Moretti se torna aventureiro em um mundo steampunk com divindades misteriosas.",
    year: 2024,
    episodes: 13,
    status: "Em andamento",
    genres: ["Cultivation", "Mystery", "Fantasy"],
    popularity: 82,
  },

  // ── HQ ─────────────────────────────────────────────────────────────────────
  {
    id: "rec_013_001",
    type: "HQ",
    title: "Watchmen",
    author: "Alan Moore",
    synopsis:
      "Em uma realidade alternativa, heróis aposentados investigam a morte de um de seus membros.",
    year: 1986,
    issues: 12,
    status: "Concluído",
    genres: ["Superhero", "Mystery", "Political"],
    popularity: 95,
  },
  {
    id: "rec_013_002",
    type: "HQ",
    title: "Batman: O Cavaleiro das Trevas",
    author: "Frank Miller",
    synopsis: "Batman retorna em um futuro distópico para salvar Gotham City.",
    year: 1986,
    issues: 4,
    status: "Concluído",
    genres: ["Superhero", "Action", "Dystopian"],
    popularity: 94,
  },
  {
    id: "rec_013_003",
    type: "HQ",
    title: "Sandman",
    author: "Neil Gaiman",
    synopsis: "A história de Morpheus, o Senhor dos Sonhos, e sua jornada por mundos imaginários.",
    year: 1989,
    issues: 75,
    status: "Concluído",
    genres: ["Fantasy", "Supernatural", "Mystery"],
    popularity: 92,
  },
  {
    id: "rec_013_004",
    type: "HQ",
    title: "Invencível",
    author: "Robert Kirkman",
    synopsis:
      "Mark Grayson herda os superpoderes do pai e descobre que o mundo dos heróis é mais sombrio do que imaginou.",
    year: 2003,
    issues: 144,
    status: "Concluído",
    genres: ["Superhero", "Action", "Drama"],
    popularity: 89,
  },
  {
    id: "rec_013_005",
    type: "HQ",
    title: "The Walking Dead",
    author: "Robert Kirkman",
    synopsis:
      "Em um mundo infestado de zumbis, sobreviventes lutam para encontrar um lugar seguro.",
    year: 2003,
    issues: 193,
    status: "Concluído",
    genres: ["Horror", "Survival", "Drama"],
    popularity: 90,
  },
  {
    id: "rec_013_006",
    type: "HQ",
    title: "Saga",
    author: "Brian K. Vaughan",
    synopsis: "Dois soldados de raças alienígenas em guerra se apaixonam e fogem com sua filha.",
    year: 2012,
    issues: 60,
    status: "Em andamento",
    genres: ["Sci-Fi", "Fantasy", "Drama"],
    popularity: 91,
  },
  {
    id: "rec_013_007",
    type: "HQ",
    title: "V de Vingança",
    author: "Alan Moore",
    synopsis: "Em uma Inglaterra fascista, um vigilante mascarado luta contra o regime opressor.",
    year: 1982,
    issues: 10,
    status: "Concluído",
    genres: ["Superhero", "Political", "Thriller"],
    popularity: 89,
  },

  // ── Fanfic ─────────────────────────────────────────────────────────────────
  {
    id: "rec_012_001",
    type: "Fanfic",
    title: "O Diabo Veste Branco",
    author: "ET-Black / OPWonders",
    synopsis:
      "O trio ASL é sequestrado e levado a um lugar de pesadelo, testado enquanto tenta escapar.",
    year: 2022,
    words: 187000,
    chapters: 100,
    fandom: "One Piece",
    status: "Concluído",
    genres: ["Ação", "Angústia", "Sobrevivência"],
    popularity: 92,
  },
  {
    id: "rec_012_002",
    type: "Fanfic",
    title: "Este Capitão Veste Vermelho",
    author: "ET-Black / OPWonders",
    synopsis:
      "Luffy segue em frente em direção ao seu sonho de se tornar o Rei dos Piratas. Sequência de 'O Diabo Veste Branco'.",
    year: 2025,
    words: 27500,
    chapters: 41,
    fandom: "One Piece",
    status: "Em andamento",
    genres: ["Ação", "Aventura", "Angústia"],
    popularity: 85,
  },
  {
    id: "rec_012_003",
    type: "Fanfic",
    title: "Deku? Eu Acho Que Ele É Um Profissional...",
    author: "Nash_Miller0 / myheadinthecoudsnotcomingdown",
    synopsis:
      "Izuku decide ajudar heróis com sua análise e acaba chamando a atenção de vários profissionais.",
    year: 2023,
    words: 98400,
    chapters: 94,
    fandom: "Boku no Hero Academia",
    status: "Concluído",
    genres: ["Ação", "Análise", "Drama"],
    popularity: 90,
  },
  {
    id: "rec_012_004",
    type: "Fanfic",
    title: "Mastermind: Ascensão da Anarquia",
    author: "g_4by_ / Clouds",
    synopsis: "Izuku Midoriya, o Mastermind, está preso, mas sua influência na sociedade continua.",
    year: 2023,
    words: 115000,
    chapters: 50,
    fandom: "Boku no Hero Academia",
    status: "Concluído",
    genres: ["Vilão!Deku", "Angústia", "Crime"],
    popularity: 88,
  },
  {
    id: "rec_012_005",
    type: "Fanfic",
    title: "Quando estamos juntos (não tenho medo das minhas lágrimas)",
    author: "Deve ter sido o vento",
    synopsis:
      "Dazai e Chuuya são 'forçados' a frequentar a UA depois de matarem um herói em uma transmissão ao vivo.",
    year: 2023,
    words: 277584,
    chapters: 39,
    fandom: "Bungou Stray Dogs / My Hero Academia",
    status: "Em andamento",
    genres: ["Crossover", "Ação", "Drama", "Romance"],
    popularity: 95,
  },
  {
    id: "rec_012_006",
    type: "Fanfic",
    title: "A Luz Entre Nós",
    author: "TheLacedNinja",
    synopsis: "Dazai e Chuuya sempre pareceram se odiar, mas um fio vermelho do destino os uniu.",
    year: 2023,
    words: 310306,
    chapters: 37,
    fandom: "Bungou Stray Dogs",
    status: "Concluído",
    genres: ["Omegaverse", "Drama", "Romance"],
    popularity: 89,
  },
  {
    id: "rec_012_007",
    type: "Fanfic",
    title: "Uma Segunda Chance - Kaigaku",
    author: "SemideusaDeSonserina",
    synopsis:
      "Kaigaku é morto por Zenitsu e acaba voltando no tempo — seria essa sua segunda chance?",
    year: 2024,
    words: 55100,
    chapters: 43,
    fandom: "Demon Slayer",
    status: "Concluído",
    genres: ["Viagem no Tempo", "Redenção", "Romance"],
    popularity: 84,
  },
  {
    id: "rec_012_008",
    type: "Fanfic",
    title: "Como assim ele é um bebê?!",
    author: "Nightfire1023",
    synopsis:
      "Giyuu se transforma em bebê após uma Arte de Sangue Demoníaca e os Hashira precisam lidar com isso.",
    year: 2024,
    words: 44375,
    chapters: 26,
    fandom: "Demon Slayer",
    status: "Concluído",
    genres: ["Fofura", "Regressão de Idade", "Angústia"],
    popularity: 91,
  },
  {
    id: "rec_012_009",
    type: "Fanfic",
    title: "As engrenagens começam a girar",
    author: "RikaSyah",
    synopsis:
      "Kamado Sumihiko e Rengoku Toujirou são lançados de volta no tempo e precisam navegar por um mundo de demônios.",
    year: 2025,
    words: 452954,
    chapters: 59,
    fandom: "Demon Slayer",
    status: "Em andamento",
    genres: ["Viagem no Tempo", "Ação/Aventura", "Mistério"],
    popularity: 86,
  },
  {
    id: "rec_012_010",
    type: "Fanfic",
    title: "Atingido duas vezes",
    author: "Vaellean",
    synopsis:
      "Giyuu não entende como um covarde como Zenitsu poderia ter alcançado o nível de Hashira.",
    year: 2023,
    words: 86675,
    chapters: 19,
    fandom: "Demon Slayer",
    status: "Concluído",
    genres: ["Ação/Aventura", "Dor/Conforto", "BAMF Zenitsu"],
    popularity: 88,
  },
];

type ScoredItem = RecommendationItem & { _score: number };

// Calcula score de cada item baseado no perfil do usuário + popularidade
export function scoreItems(catalog: RecommendationItem[], works: Work[]): RecommendationItem[] {
  if (works.length === 0) {
    return [...catalog].sort((a, b) => b.popularity - a.popularity);
  }

  // Conta tipos e gêneros do usuário
  const typeCounts: Record<string, number> = {};
  const genreCounts: Record<string, number> = {};

  for (const w of works) {
    typeCounts[w.type] = (typeCounts[w.type] ?? 0) + 1;
    (w.genres ?? []).forEach((g) => {
      genreCounts[g] = (genreCounts[g] ?? 0) + 1;
    });
  }

  const maxType = Math.max(...Object.values(typeCounts), 1);
  const maxGenre = Math.max(...Object.values(genreCounts), 1);

  return [...catalog]
    .map((item): ScoredItem => {
      const typeScore = ((typeCounts[item.type] ?? 0) / maxType) * 40;
      const genreScore =
        item.genres.reduce((sum, g) => sum + (genreCounts[g] ?? 0), 0) /
        (item.genres.length * maxGenre) * 40;
      const popularityScore = (item.popularity / 100) * 20;
      return { ...item, _score: typeScore + genreScore + popularityScore };
    })
    .sort((a, b) => b._score - a._score);
}

export function getByType(
  scored: RecommendationItem[],
  type: string,
  limit = 10,
): RecommendationItem[] {
  return scored.filter((i) => i.type === type).slice(0, limit);
}

export function getTrending(scored: RecommendationItem[], limit = 10): RecommendationItem[] {
  return [...scored].sort((a, b) => b.popularity - a.popularity).slice(0, limit);
}

export function toNum(v: unknown): number | undefined {
  if (typeof v === "number" && !Number.isNaN(v)) return v;
  if (typeof v === "string" && v.trim() && v.trim() !== "?") {
    const n = Number(v);
    return Number.isNaN(n) ? undefined : n;
  }
  return undefined;
}

// Converte uma recomendação pública (postada por um usuário real) para o
// mesmo formato usado nas telas de recomendação e na página de visualização.
export function communityToRecommendationItem(r: PostedRecommendation): RecommendationItem {
  const d = r.details || {};
  return {
    id: `community_${r.id}`,
    type: r.type,
    title: r.title,
    author: r.author || "",
    synopsis: "",
    year: new Date(r.createdAt).getFullYear(),
    status: "",
    genres: r.genres || [],
    popularity: Math.round((r.rating || 0) * 20),
    recommendedBy: r.username,
    cover: r.cover,
    rating: r.rating,
    notes: r.notes,
    link: r.link,
    studio: (d.studio as string) || undefined,
    tags: (d.tags as string[]) || undefined,
    reactions: (d.reactions as string[]) || undefined,
    episodes: toNum(d.totalEpisodes),
    chapters: toNum(d.totalChapters),
    volumes: toNum(d.totalVolumes),
    seasons: toNum(d.totalSeasons),
    duration: toNum(d.duration),
    hours: toNum(d.hours),
    issues: toNum(d.totalIssues),
    platform: (d.platform as string) || undefined,
    related: (d.related as RelatedWork[]) || undefined,
  };
}
