/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WrappedRouteImport } from './routes/wrapped'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SplashRouteImport } from './routes/splash'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProRouteImport } from './routes/pro'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as AwardsRouteImport } from './routes/awards'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AddRouteImport } from './routes/add'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddIndexRouteImport } from './routes/add.index'
import { Route as WorkIdRouteImport } from './routes/work.$id'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as RecIdRouteImport } from './routes/rec.$id'
import { Route as ChatUidRouteImport } from './routes/chat.$uid'
import { Route as AddTypeRouteImport } from './routes/add.$type'
import { Route as WorkIdEditRouteImport } from './routes/work_.$id.edit'

const WrappedRoute = WrappedRouteImport.update({
  id: '/wrapped',
  path: '/wrapped',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardsRoute = AwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddIndexRoute = AddIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AddRoute,
} as any)
const WorkIdRoute = WorkIdRouteImport.update({
  id: '/work/$id',
  path: '/work/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const RecIdRoute = RecIdRouteImport.update({
  id: '/rec/$id',
  path: '/rec/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatUidRoute = ChatUidRouteImport.update({
  id: '/chat/$uid',
  path: '/chat/$uid',
  getParentRoute: () => rootRouteImport,
} as any)
const AddTypeRoute = AddTypeRouteImport.update({
  id: '/$type',
  path: '/$type',
  getParentRoute: () => AddRoute,
} as any)
const WorkIdEditRoute = WorkIdEditRouteImport.update({
  id: '/work_/$id/edit',
  path: '/work/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add': typeof AddRouteWithChildren
  '/admin': typeof AdminRoute
  '/awards': typeof AwardsRoute
  '/challenges': typeof ChallengesRoute
  '/collections': typeof CollectionsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/friends': typeof FriendsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/pro': typeof ProRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/splash': typeof SplashRoute
  '/stats': typeof StatsRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/wrapped': typeof WrappedRoute
  '/add/$type': typeof AddTypeRoute
  '/chat/$uid': typeof ChatUidRoute
  '/rec/$id': typeof RecIdRoute
  '/u/$username': typeof UUsernameRoute
  '/work/$id': typeof WorkIdRoute
  '/add/': typeof AddIndexRoute
  '/work/$id/edit': typeof WorkIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/awards': typeof AwardsRoute
  '/challenges': typeof ChallengesRoute
  '/collections': typeof CollectionsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/friends': typeof FriendsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/pro': typeof ProRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/splash': typeof SplashRoute
  '/stats': typeof StatsRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/wrapped': typeof WrappedRoute
  '/add/$type': typeof AddTypeRoute
  '/chat/$uid': typeof ChatUidRoute
  '/rec/$id': typeof RecIdRoute
  '/u/$username': typeof UUsernameRoute
  '/work/$id': typeof WorkIdRoute
  '/add': typeof AddIndexRoute
  '/work/$id/edit': typeof WorkIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add': typeof AddRouteWithChildren
  '/admin': typeof AdminRoute
  '/awards': typeof AwardsRoute
  '/challenges': typeof ChallengesRoute
  '/collections': typeof CollectionsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/friends': typeof FriendsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/pro': typeof ProRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/splash': typeof SplashRoute
  '/stats': typeof StatsRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/wrapped': typeof WrappedRoute
  '/add/$type': typeof AddTypeRoute
  '/chat/$uid': typeof ChatUidRoute
  '/rec/$id': typeof RecIdRoute
  '/u/$username': typeof UUsernameRoute
  '/work/$id': typeof WorkIdRoute
  '/add/': typeof AddIndexRoute
  '/work_/$id/edit': typeof WorkIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/add'
    | '/admin'
    | '/awards'
    | '/challenges'
    | '/collections'
    | '/forgot-password'
    | '/friends'
    | '/library'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/privacy'
    | '/pro'
    | '/profile'
    | '/recommendations'
    | '/register'
    | '/search'
    | '/settings'
    | '/splash'
    | '/stats'
    | '/terms'
    | '/verify-email'
    | '/wrapped'
    | '/add/$type'
    | '/chat/$uid'
    | '/rec/$id'
    | '/u/$username'
    | '/work/$id'
    | '/add/'
    | '/work/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/awards'
    | '/challenges'
    | '/collections'
    | '/forgot-password'
    | '/friends'
    | '/library'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/privacy'
    | '/pro'
    | '/profile'
    | '/recommendations'
    | '/register'
    | '/search'
    | '/settings'
    | '/splash'
    | '/stats'
    | '/terms'
    | '/verify-email'
    | '/wrapped'
    | '/add/$type'
    | '/chat/$uid'
    | '/rec/$id'
    | '/u/$username'
    | '/work/$id'
    | '/add'
    | '/work/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/add'
    | '/admin'
    | '/awards'
    | '/challenges'
    | '/collections'
    | '/forgot-password'
    | '/friends'
    | '/library'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/privacy'
    | '/pro'
    | '/profile'
    | '/recommendations'
    | '/register'
    | '/search'
    | '/settings'
    | '/splash'
    | '/stats'
    | '/terms'
    | '/verify-email'
    | '/wrapped'
    | '/add/$type'
    | '/chat/$uid'
    | '/rec/$id'
    | '/u/$username'
    | '/work/$id'
    | '/add/'
    | '/work_/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AddRoute: typeof AddRouteWithChildren
  AdminRoute: typeof AdminRoute
  AwardsRoute: typeof AwardsRoute
  ChallengesRoute: typeof ChallengesRoute
  CollectionsRoute: typeof CollectionsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  FriendsRoute: typeof FriendsRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProRoute: typeof ProRoute
  ProfileRoute: typeof ProfileRoute
  RecommendationsRoute: typeof RecommendationsRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SplashRoute: typeof SplashRoute
  StatsRoute: typeof StatsRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  WrappedRoute: typeof WrappedRoute
  ChatUidRoute: typeof ChatUidRoute
  RecIdRoute: typeof RecIdRoute
  UUsernameRoute: typeof UUsernameRoute
  WorkIdRoute: typeof WorkIdRoute
  WorkIdEditRoute: typeof WorkIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wrapped': {
      id: '/wrapped'
      path: '/wrapped'
      fullPath: '/wrapped'
      preLoaderRoute: typeof WrappedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awards': {
      id: '/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add/': {
      id: '/add/'
      path: '/'
      fullPath: '/add/'
      preLoaderRoute: typeof AddIndexRouteImport
      parentRoute: typeof AddRoute
    }
    '/work/$id': {
      id: '/work/$id'
      path: '/work/$id'
      fullPath: '/work/$id'
      preLoaderRoute: typeof WorkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rec/$id': {
      id: '/rec/$id'
      path: '/rec/$id'
      fullPath: '/rec/$id'
      preLoaderRoute: typeof RecIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$uid': {
      id: '/chat/$uid'
      path: '/chat/$uid'
      fullPath: '/chat/$uid'
      preLoaderRoute: typeof ChatUidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add/$type': {
      id: '/add/$type'
      path: '/$type'
      fullPath: '/add/$type'
      preLoaderRoute: typeof AddTypeRouteImport
      parentRoute: typeof AddRoute
    }
    '/work_/$id/edit': {
      id: '/work_/$id/edit'
      path: '/work/$id/edit'
      fullPath: '/work/$id/edit'
      preLoaderRoute: typeof WorkIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AddRouteChildren {
  AddTypeRoute: typeof AddTypeRoute
  AddIndexRoute: typeof AddIndexRoute
}

const AddRouteChildren: AddRouteChildren = {
  AddTypeRoute: AddTypeRoute,
  AddIndexRoute: AddIndexRoute,
}

const AddRouteWithChildren = AddRoute._addFileChildren(AddRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AddRoute: AddRouteWithChildren,
  AdminRoute: AdminRoute,
  AwardsRoute: AwardsRoute,
  ChallengesRoute: ChallengesRoute,
  CollectionsRoute: CollectionsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  FriendsRoute: FriendsRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  ProRoute: ProRoute,
  ProfileRoute: ProfileRoute,
  RecommendationsRoute: RecommendationsRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SplashRoute: SplashRoute,
  StatsRoute: StatsRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  WrappedRoute: WrappedRoute,
  ChatUidRoute: ChatUidRoute,
  RecIdRoute: RecIdRoute,
  UUsernameRoute: UUsernameRoute,
  WorkIdRoute: WorkIdRoute,
  WorkIdEditRoute: WorkIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
